### ISSUE TITLE
fuse-overlay needs to support readonly lower with no upper.

### ISSUE THREAD

**Issue by rhatdan** [containers/fuse-overlayfs#100]
Containers storage, has a fix that allows additional-stores to be mounted read/only, but this requires the mounting of multi-layer lowers without an upper directory.  Currently fuse-overlay does not support this and is has to be disabled from this feature.

**Comment by rhatdan** [comment]
@nalind FYI

**Comment by rhatdan** [comment]
https://github.com/containers/storage/blob/master/drivers/overlay/overlay.go#L844

**Comment by AkihiroSuda** [comment]
@giuseppe Is there any specific reason not to support read-only mode?

I'm trying to implement containerd snapshotter for fuse-overlayfs and want read-only mode

**Comment by AkihiroSuda** [comment]
These parts require read-only multi-lowerdir mount

https://github.com/containerd/containerd/blob/36c4260e6fa15cb20012cfe95f322ef85cf771ca/snapshots/overlay/overlay.go#L469-L501

**Comment by giuseppe** [comment]
> @giuseppe Is there any specific reason not to support read-only mode?

no, only I had not time to look into it yet.  It should not be too difficult as it is only a matter of checking fuse-overlayfs returns `EROFS` on each operation that attempts to modify the file system.  I'll take a look

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/containers/fuse-overlayfs/pull/133
