### ISSUE TITLE
add flag to keep the pid alive

### ISSUE THREAD

**Issue by vbatts** [containers/fuse-overlayfs#11]
add a flag to foreground the pid. This will allow for having a container act as a plumbing interface more easily.

**Comment by giuseppe** [comment]
There is an `-f` flag that is understood directly by libfuse and used for `fuse_daemonize` https://libfuse.github.io/doxygen/fuse__common_8h.html#af1857d2209952f49a762aff39f3cd8bd

Does the process stay in the foreground if you pass `-f`?

**Comment by vbatts** [comment]
nope. I'm trying it in #12

**Comment by giuseppe** [comment]
@vbatts is this still an issue or can I close it?

**Comment by vbatts** [comment]
It works as expected
