### ISSUE TITLE
buildah bud fails due to missing file system in the container

### ISSUE THREAD

**Issue by gireeshpunathil** [containers/fuse-overlayfs#116]
Failing case: missing mount binding to the parent container

```
#docker run -it --privileged quay.io/buildah/stable
[root@e8c64993a35b /]# echo 'FROM alpine' > Dockerfile
[root@e8c64993a35b /]# echo 'RUN whoami' >> Dockerfile
[root@e8c64993a35b /]# buildah bud -t foo .
STEP 1: FROM alpine
Getting image source signatures
Copying blob 9d48c3bd43c5 done
Copying config 9617696764 done
Writing manifest to image destination
Storing signatures
STEP 2: RUN whoami
process exited with error: fork/exec /bin/sh: no such file or directorysubprocess exited with status 1
                                                                                                      error building at STEP "RUN whoami": exit status 1
[root@e8c64993a35b /]# 
```

Passing case: mount binding enabled to the parent container

```
#docker run -it --privileged -v containers:/var/lib/containers quay.io/buildah/stable
[root@c4975399f13e /]# echo 'FROM alpine' > Dockerfile
[root@c4975399f13e /]# echo 'RUN whoami' >> Dockerfile
[root@c4975399f13e /]# buildah bud -t foo .
STEP 1: FROM alpine
STEP 2: RUN whoami
root
STEP 3: COMMIT foo
Getting image source signatures
Copying blob 03901b4a2ea8 skipped: already exists
Copying blob 652252567dcf done
Copying config bbf36d740b done
Writing manifest to image destination
Storing signatures
bbf36d740bc9b1defd3efb7cce0900b70f7a532863b7bc49d89c8a0c44a4d1f6
[root@c4975399f13e /]# 
```

So far so good. Now I converted this cli invocation into a tekton pipeline as follows (only the task steps are shown that is most relevant here)

```
  steps:
    - name: assemble-extract-step
      image: gireeshpunathil/foo
      command: ["/bin/bash"]
      args:
        - -c
        - "somescript.sh"
      env:
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
```

The image `gireeshpunathil/foo` is essentially a thin layer on top of `quay.io/buildah/stable`. 

This works as expected with `minikube`. (just like second case above)

This fails in minishift (just like first case above)

With my limited experience with `minishift`, I believe this has something to do with either:
 - the mount bind is not properly assigned processed with the container.
 - sufficient privilege has not yet been provided

As I am not very sure about the root cause, and as the issue is manifesting as a buildah command failure, I am raising it here. Please advise, thanks in advance!

Additional info - queried from the faulty container:

```
# mount | grep container
/dev/mapper/rhel-root on /var/lib/containers type xfs (rw,relatime,attr2,inode64,noquota)
```

```
# env | grep BUILDAH
_BUILDAH_STARTED_IN_USERNS=
BUILDAH_ISOLATION=chroot
```

excerpt from strace:
```
newfstatat(AT_FDCWD, "/var/lib/containers/storage/overlay/bd2ae87e47f432e463e519a14a27376510799b51d5a1be793297f22a760a2bf2/merged/bin/bash", 0xc000785d78, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
```

```
# ls -lrt /var/lib/containers/storage/overlay/bd2ae87e47f432e463e519a14a27376510799b51d5a1be793297f22a760a2bf2/merged/
total 0
drwx------ 2 root root  6 Aug 27 04:03 sys
drwx------ 2 root root  6 Aug 27 04:03 proc
drwx------ 2 root root  6 Aug 27 04:03 dev
d--x--x--x 3 root root 21 Aug 27 04:03 run
d--x--x--x 2 root root 38 Aug 27 04:03 etc
#
```

So! /usr and and many other system folders are missing! how this could be!

All other required info for the bug tracker (system information etc.) are precisely the same as  in https://github.com/containers/buildah/issues/1814, so not duplicating here.

**Comment by gireeshpunathil** [comment]
thanks @giuseppe ! will test and get back.

**Comment by giuseppe** [comment]
@gireeshpunathil yes the conf file looks correctly.

libfuse checks whether some features are available and informs the FUSE program (fuse-overlayfs in this case) what can be requested.  fuse-overlayfs didn't check for it, and assumed writeback is always supported, which from your bug report seems to not be the case.

PR opened here: https://github.com/containers/fuse-overlayfs/pull/117

**Comment by gireeshpunathil** [comment]
thanks all for the help, really appreciated!!

I will watch out for a release being cut out of #117 , any rough estimate on the dates?

**Comment by gireeshpunathil** [comment]
can some one advise me which `buildah` release this fix was incorporated into? the reason why I ask is, I don't see the intended behavior with latest buildah releases. cc @rhatdan @TomSweeneyRedHat @giuseppe

**Comment by nalind** [comment]
Based on the log of differences between 0.6 and 0.7 (https://github.com/containers/fuse-overlayfs/compare/v0.6...v0.7), it should have been in 0.7.

**Comment by TomSweeneyRedHat** [comment]
@gireeshpunathil as @nalind pointed out, it's in the latest release.  That being said, other than cloning and building fuse-overlayfs from  GitHub, I'm not sure where you could get a rpm yet.  @giuseppe or @lsm5 do you have any pointers?

**Comment by gireeshpunathil** [comment]
> Based on the log of differences between 0.6 and 0.7 (v0.6...v0.7), it should have been in 0.7.

@nalind - thanks, will check on that. 

I actually meant [buildah release](https://github.com/containers/buildah/releases) or [buildah container image](https://quay.io/repository/buildah/stable) that has this (good) version of `fuse-overlay`

**Comment by giuseppe** [comment]
@gireeshpunathil Buildah doesn't ship fuse-overlayfs.  It is shipped separately.

What distro are you using?  fuse-overlayfs 0.7 is already on Fedora 30/31 stable

**Comment by gireeshpunathil** [comment]
@giuseppe - ah, thanks for the information. Will check on that.

So basically we should be good if I do:

`yum update && yum install fuse-overlayfs` prior to the sequences in my first comment I guess?

**Comment by TomSweeneyRedHat** [comment]
@gireeshpunathil I'd go with `yum update && yum update fuse-overlayfs`, then `rpm -qa | grep overlayfs`, and verify the version.

**Comment by gireeshpunathil** [comment]
@TomSweeneyRedHat - thanks. My main question (I acknowledge that did not come good) was whether we update `fuse-overlayfs` on the host, or inside the (buildah) container?

**Comment by TomSweeneyRedHat** [comment]
@gireeshpunathil ah!  Should only be on the host side that you will need to update fuse-overlayfs on, the container should be fine.

**Comment by gireeshpunathil** [comment]
thanks @TomSweeneyRedHat for the clarification!
