### ISSUE TITLE
Static build instructions: unknown flag: --device

### ISSUE THREAD

**Issue by about-code** [containers/fuse-overlayfs#130]
[README.md, Section "Static Build", Step 4](https://github.com/containers/fuse-overlayfs/commit/1d83907f301620256ea7eaae056d103885b55443#diff-04c6e90faac2675aa89e2176d2eec7d8R56) says:

```
buildah bud --device /dev/fuse -t fuse-overlayfs -f ./Dockerfile.static .
```

#### Expected:

build starts

#### Actual:

```
unknown flag: --device
```

#### Version information:
```
buildah --version
buildah version 1.10.1 (image-spec 1.0.1, runtime-spec 1.0.1-dev)
```

Tried on:
- Ubuntu 18.04 LTS

**Comment by rhatdan** [comment]
You need a newer version of buildah 
```
$ buildah bud --help | grep device
      --device stringArray            Additional devices to be used within containers (default [])
$ /usr/bin/buildah version
Version:         1.11.3
Go Version:      go1.13
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Comment by about-code** [comment]
@rhatdan, thanks for your response. 

I have been installing Buildah following the [Buildah install instructions for Ubuntu](https://github.com/containers/buildah/blob/master/install.md#ubuntu) users as they have been linked in [Step 1](https://github.com/containers/fuse-overlayfs/commit/1d83907f301620256ea7eaae056d103885b55443#diff-04c6e90faac2675aa89e2176d2eec7d8R43), so:

```
sudo apt-get update -qq
sudo apt-get install -qq -y software-properties-common
sudo add-apt-repository -y ppa:projectatomic/ppa
sudo apt-get update -qq
sudo apt-get -qq -y install buildah
```

But  `buildah (1.10.1-1~ubuntu18.04~ppa1)` seems to be the newest version I get. 

I am particularly interested in the static build since this is mentioned to be the alternative for people who can not satisfy the prerequistes under section *Requirements* (e.g. Ubuntu > v19.04) which is likely to be any user of a current Ubuntu 18.04 LTS Release (Bionic Beaver). 

I got here by following the [installation instructions for rootless podman](https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md#ensure-fuse-overlayfs-is-installed) but it seems I am reaching a dead end.

**Comment by rhatdan** [comment]
@lsm5 PTAL
