### ISSUE TITLE
setattr fails with readonly /proc

### ISSUE THREAD

**Issue by 3XX0** [containers/fuse-overlayfs#137]
`setattr` fails if `/proc` is mounted as readonly. It used to work at some point but now that symlinks are handled through `/proc/self/fd` it will fail with `EROFS`.

AFAIK it's not easily fixable with the current logic since we're opening the fd on the symlink early on
and  syscalls like `utimensat` won't work on symlink fds.

https://github.com/containers/fuse-overlayfs/blob/1faf62ce32f2bab09d593b61a44af76e08639ffa/main.c#L3309-L3317 

Is there a reason not to rely on things like `utimensat(dirfd,...)`, `fchownat`, `fchmodat` instead?

**Comment by giuseppe** [comment]
the reason for that is that `fchmodat` doesn't support `AT_SYMLINK_NOFOLLOW`.  Going through `/proc` is the only workaround I've found to that limitation

**Comment by 3XX0** [comment]
You're right, my bad I trusted the [man page](https://github.com/mkerrisk/man-pages/blob/master/man7/symlink.7#L137).
I thought you could use `NULL` or `AT_EMPTY_PATH` but looking at the kernel source there is no way.

Should this be mentioned somewhere then? Getting `EROFS` on a r/w mount is certainly surprising.

**Comment by giuseppe** [comment]
we could probably add a test when `fuse-overlayfs` starts and if there is a upperdir directory specified then we also check that `/proc/self/fd/X` can be opened with `O_WRONLY`.  What do you think?  It can give a more helpful error and inform the user that `/proc` must be present and writeable

**Comment by 3XX0** [comment]
Yeah that's a good idea, it doesn't have to be fatal a warning could be enough

**Comment by giuseppe** [comment]
and finally opened a PR: https://github.com/containers/fuse-overlayfs/pull/372
