### ISSUE TITLE
Spurious files in a directory marked as opaque

### ISSUE THREAD

**Issue by msimacek** [containers/fuse-overlayfs#138]
https://github.com/containers/fuse-overlayfs/issues/136 is currently fixed for the case when the directory is marked with a whiteout file (I tested this), but it is still reproducible in the second variant where the directory is marked opaque. Reproducer:
```Dockerfile
FROM busybox

RUN mkdir -p /dir1/dir2
RUN touch /dir1/dir2/foo
RUN rm -r /dir1 && mkdir -p /dir1
```
The image has to be built with docker in this case, buildah doesn't generate opaque directories. In this case the `/dir1` gets marked as opaque. When run with unpriviledged podman (using fuse-overlayfs from current master branch), the `foo` file is still visible.

**Comment by giuseppe** [comment]
how did you move the image from Docker to Podman?  Have you pushed it to a registry?

Is the image available at a public registry that I can just pull it?

**Comment by msimacek** [comment]
Hi, pushed it to a local registry.
```bash
docker run -d -p 5000:5000 --restart=always --name registry registry
docker build . -t localhost:5000/test/opaque
docker push localhost:5000/test/opaque
podman pull --tls-verify=false localhost:5000/test/opaque
podman run -it --rm localhost:5000/test/opaque
```

**Comment by giuseppe** [comment]
I've manually created one test case, as I could not build the image with the version of Docker I've tried.

Could you please verify if https://github.com/containers/fuse-overlayfs/pull/139 solves the issue you've seen?

**Comment by msimacek** [comment]
I tried the PR, but podman didn't even start. I suspect that the overlay segfaulted.

I pushed the image to dockerhub, so you can test it:
```bash
podman run --rm -it msimacek/fuse-overlayfs-reproducer:opaque
```

**Comment by giuseppe** [comment]
could it be selinux blocking it?

Thanks for pushing the image, I've just verified it works locally with the PR I've opened:

```
$ podman run --rm -it msimacek/fuse-overlayfs-reproducer:opaque ls -la /dir1
total 0
drwxr-xr-x    2 root     root            26 Nov  1 10:54 .
drwxr-xr-x    4 root     root            29 Nov  1 16:44 ..
```

**Comment by msimacek** [comment]
> could it be selinux blocking it?

No, I was able to test the same way with master and it didn't crash. Anyway, I tested your PR now it didn't crash and it fixed the problem for opaque directories for me. Thank you for the fix.

**Comment by rhatdan** [comment]
Closing issue.

**Comment by msimacek** [comment]
@rhatdan Note the PR which fixes this is not yet merged
