### ISSUE TITLE
Feature Requirement: port to MAC OS

### ISSUE THREAD

**Issue by butterflyfish** [containers/fuse-overlayfs#140]
SSHFS works well on MAC with help of osxfuse. Is it possible to port fuse-overlayfs to MAC OS ?

**Comment by christian-korneck** [comment]
an alternative that seems to work on Darwin is [rpodgorny/unionfs-fuse](https://github.com/rpodgorny/unionfs-fuse)

**Comment by giuseppe** [comment]
MAC OS support is out of scope for fuse-overlayfs since there are many assumptions all over the code that is running on Linux.

If anyone is interested to work on it though, I'll happily review the patches
