### ISSUE TITLE
Are remote / network filesystems supported as upperdir?

### ISSUE THREAD

**Issue by andrewsali** [containers/fuse-overlayfs#141]
Hi,

In kernel overlay there are restrictions to explicitly prohibit network based / remote filesystems (e.g. CephFS) as upperdir: https://github.com/torvalds/linux/blob/b41dae061bbd722b9d7fa828f35d22035b218e18/fs/overlayfs/super.c#L754

I was wondering about the implementation of fuse-overlayfs, whether it would support such filesystems? In particular whether it would  support filesystems where dcache is not necessarily up-to-date. (https://lwn.net/Articles/649115/ - "More than just a cache" section)

Many thanks,

Andras

**Comment by giuseppe** [comment]
we don't disable that, but to my knowledge it wasn't tested.  Have you already tried to run it with CephFS?

**Comment by andrewsali** [comment]
I haven't been able to test with CephFS yet, having some issues with using the static build on that machine, the "merged" folder is returning a bunch of ???-s:

```
[salia@'h:ofs-test ] $ls -laht
ls: cannot access 'merged': Invalid argument
total 20K
drwxr-xr-x  3 salia domain users 4.0K Nov 11 15:36 workdir
drwxr-xr-x  6 salia domain users 4.0K Nov 11 15:36 .
drwxr-xr-x  2 salia domain users 4.0K Nov 11 15:36 upperdir
drwxr-xr-x  2 salia domain users 4.0K Nov 11 15:36 lowerdir
drwxrwxrwt 13 root  root         4.0K Nov 11 15:36 ..
d?????????  ? ?     ?               ?            ? merged
```

I tried on my local machine with sshfs as upperdir / workdir, unfortunately if I change the files remotely (e.g. add a new file), it shows up properly in sshfs based upperdir, but the merged directory is not showing the changes. If I remount the overlayfs, then it shows up. Is there maybe some cache setting that could be set up to invalidate after a certain amount of time so that changes that were done remotely get picked up?

**Comment by giuseppe** [comment]
yes, I think you would like to tweak `-o timeout=N`, where with N=0 the caching is disabled.

**Comment by andrewsali** [comment]
With N=0, the problem is gone, however with anything larger, it seems the cache is never invalidated. Can it be a problem that the underlying FS of the overlay is another fuse mount?

**Comment by andrewsali** [comment]
Closing this as with N=0 it seems to work with remote filesystems.

**Comment by lengrongfu** [comment]
@andrewsali Please help me, how to user sshfs + fuse-overlayfs to remote / network filesystems supported as upperdir.
