### ISSUE TITLE
Minimum required kernel version

### ISSUE THREAD

**Issue by andrewsali** [containers/fuse-overlayfs#142]
Hi,

When trying to use the static build across hosts, we only managed to properly use the binary with relatively new kernels (in our config it works with 4.15.0-66).

On machines with older kernels (we tested 4.04 and also below, on Ubuntu and CentOS systems), the merged directory didn't work:

```
[salia@'h:ofs-test ] $ls -laht
ls: cannot access 'merged': Invalid argument
total 20K
drwxr-xr-x  3 salia domain users 4.0K Nov 11 15:36 workdir
drwxr-xr-x  6 salia domain users 4.0K Nov 11 15:36 .
drwxr-xr-x  2 salia domain users 4.0K Nov 11 15:36 upperdir
drwxr-xr-x  2 salia domain users 4.0K Nov 11 15:36 lowerdir
drwxrwxrwt 13 root  root         4.0K Nov 11 15:36 ..
d?????????  ? ?     ?               ?            ? merged
```

Is there some required minimum kernel version for using the statically built fuse-overlayfs binary?

Thanks,

Andras

**Comment by rhatdan** [comment]
I know that non root fuse-overlay mounts is not supported in a user namespace in RHEL7/Centos7.  We hope to have  a fix for this in RHEL7.8 release.

**Comment by andrewsali** [comment]
The mount was done using sudo, in that case should it be expected to work on Centos7?

**Comment by rhatdan** [comment]
Then their might be a flag in overlay mounts that was not supported yet.

**Comment by andrewsali** [comment]
Ok, thanks - closing this, for future reference to others, the minimum needed kernel version is probably somewhere between 4.04 and 4.15.
