### ISSUE TITLE
EOVERFLOW when issuing fdatasync on a directory via aio interface

### ISSUE THREAD

**Issue by avikivity** [containers/fuse-overlayfs#148]
The following program:

```c
#include <unistd.h>
#include <fcntl.h>
#include <libaio.h>

int main(int ac, char** av) {
    io_context_t ioc = 0;
    io_setup(1, &ioc);
    int fd = open(av[1], O_RDONLY|O_CLOEXEC);
    struct iocb iocb;
    io_prep_fdsync(&iocb, fd);
    struct iocb* iocbs[1] = { &iocb };
    io_submit(ioc, 1, iocbs);
    struct io_event events[1];
    io_getevents(ioc, 1, 1, events, NULL);
    close(fd);
    io_destroy(ioc);
    return 0;
}
```

(compile using `gcc -laio -o fdsync fdsync.c`) fails to fdatasync a directory in a fuse-overlayfs filesystem, with errno EOVERFLOW (see -75 below). It works on the host.

```
# strace ./fdsync /
<snip>
io_setup(1, [140199042703360])          = 0
open("/", O_RDONLY|O_CLOEXEC)           = 3
io_submit(140199042703360, 1, [{fdsync, fildes=3}]) = 1
io_getevents(140199042703360, 1, 1, [{data=0, obj=0x7ffdf35c72e0, res=-75, res2=0}], NULL) = 1
<snip>
```

A direct call to fdatasync() works, and the aio version works on the host. It may be that fuse is itself broken, but I thought to try here first.

Linux 5.3.11-200.fc30.x86_64, fuse-overlayfs-0.6.5-2.fc30.x86_64

**Comment by giuseppe** [comment]
thanks for the reproducer.  That is indeed an issue in FUSE when running in a user namespace.  I could replicate it with sshfs as well.

The following patch in the kernel seems to fix it:

```
diff --git a/fs/fuse/dev.c b/fs/fuse/dev.c
index dadd617d826c..020b3ea02e4d 100644
--- a/fs/fuse/dev.c
+++ b/fs/fuse/dev.c
@@ -141,11 +141,6 @@ static struct fuse_req *fuse_get_req(struct fuse_conn *fc, bool for_background)
        if (for_background)
                __set_bit(FR_BACKGROUND, &req->flags);
 
-       if (unlikely(req->in.h.uid == ((uid_t)-1) ||
-                    req->in.h.gid == ((gid_t)-1))) {
-               fuse_put_request(fc, req);
-               return ERR_PTR(-EOVERFLOW);
-       }
        return req;
```

it should not matter to FUSE whether the user is not mapped inside of the user namespace.  I'll discuss it with the kernel maintainers.

**Comment by avikivity** [comment]
Closing since the bug is not in fuse-overlayfs. Please copy me (avi@scylladb.com) on the kernel patch.

**Comment by avikivity** [comment]
Looks like the patch never got applied :(
