### ISSUE TITLE
uid/gid shifting without the overlay part

### ISSUE THREAD

**Issue by Stephen-AI** [containers/fuse-overlayfs#157]
Is it possible to use fuse-overlayfs for shifting uid/gids only as opposed to both overlay and shiftfs.

**Comment by giuseppe** [comment]
not directly, but you could use an empty lower dir so that only the upper dir holds the files.

Would that work for you?

**Comment by rhatdan** [comment]
Not sure on the state of this issue?  @Stephen-AI @giuseppe What should we do with it?

**Comment by Stephen-AI** [comment]
Sorry this issue should be closed by now. I ended up using both features.
