### ISSUE TITLE
GitHub releases and version compatibility 

### ISSUE THREAD

**Issue by saschagrunert** [containers/fuse-overlayfs#159]
Hey :wave:, I found out that fuse-overlayfs v0.5.2 got incompatible with buildah v1.12.0 (committing of rootless images does not work any more), where I saw that this project does not use GitHub releases. This means that I've missed the notifications about new releases which lead into outdated packages in some distrustions.

Do you think we can use the usual GitHub releases as well as maintaining a change log there? :innocent: I'm happy to help you with that if you want.

**Comment by giuseppe** [comment]
Sure!  I thought I was doing it right here: https://github.com/containers/fuse-overlayfs/releases :-)

What more should be done?  And yes please, some help is welcome

**Comment by saschagrunert** [comment]
Hm, is it possible that you've just pushed an annotated tag into the repository? I think we notify others only for releases when using the web interface and creating an actual release with notes. :thinking:

**Comment by rhatdan** [comment]
You need to go on github.com and actually create the release. I have just created the initial release.  Going forward we should create new releases with the changelog.

**Comment by giuseppe** [comment]
new release done using the suggested process: https://github.com/containers/fuse-overlayfs/releases/tag/v0.7.3

I am going to close the issue
