### ISSUE TITLE
moving to rootless-containers

### ISSUE THREAD

**Issue by cyphar** [containers/fuse-overlayfs#16]
Would you be interested in moving this project to https://github.com/rootless-containers? This project is going to be one of the recommended deployments of rootless containers (on new enough kernels) and given that it's primary use is for rootless containers it seems a bit odd to have it in https://github.com/containers (given that the project mostly hosts `cri-o`-related projects).

WDYT @giuseppe? (Obviously you'd still have the same admin rights for rootless-containers as you have here -- there would be no practical difference from that standpoint).

**Comment by giuseppe** [comment]
hi @cyphar.  fuse-overlayfs compared to overlay in the kernel has an additional feature for UID/GID shifting so that it is not needed to chown an image when a different user namespace mapping is used and that can sometimes be useful for root containers as well.  In any case, as you said the main focus is rootless containers,  It works either way for me.  @rhatdan what do you think?

**Comment by rhatdan** [comment]
Well I would argue a that github.com/containers has a lot more stuff then just CRI-O related projects.  Podman and soon to hold buildah are not tied in any way to CRI-O.  container-selinux is used by every container runtime that uses SELinux, including rootless containers.

 Fuse-overlay can be used by podman and launched via containers/storage. I would love to see the rootless projects come over to github.com/containers.  But I don't see a reason to move fuse-overlayfs away from containers/storage.

**Comment by cyphar** [comment]
> Well I would argue a that github.com/containers has a lot more stuff then just CRI-O related projects. Podman and soon to hold buildah are not tied in any way to CRI-O.

Replace "cri-o" with "libpod" -- sorry for using the old terminology. :smile_cat:

> I would love to see the rootless projects come over to github.com/containers.

The main reason why I feel it makes more sense separately is that putting it in with github.com/containers would dilute the work we're doing in rootless containers (which is still a pretty niche and weird thing) with the rest of the github.com/containers namespace that includes a lot of libraries that are primarily used by libpod (or are just general purpose container-y things if you prefer I put it like that).

**Comment by giuseppe** [comment]
The current situation is that projects useful for rootless containers are splitted between the two organizations.  Rootless support is a first class citizen for Podman/Buildah and has been my main focus for the last months.  In facts, both slirp4netns and fuse-overlayfs are part of RHEL 8 Beta now.

@cyphar @rhatdan @AkihiroSuda would it make sense to merge both organizations?

**Comment by rhatdan** [comment]
I would love to see these all under github.com/containers, since they would be easier to find, and github.com/containers is easier to type then github.com/rootless-containers.  

Putting fuse-overlay into only rootless-containers seems to limit its potential.  Could I run fuse-overlay within a podman container running on an overlay file system?

**Comment by giuseppe** [comment]
yes it is possible to use fuse-overlayfs from a root container and it works on top of an existing overlay mount (in this case we will use `.wh.` whiteouts as we do with rootless containers)

**Comment by AkihiroSuda** [comment]
W.r.t.  https://github.com/rootless-containers/usernetes , I'd like to move it to https://github.com/kubernetes-sigs in future, with help from either SIG-node or/and SIG-cluster-lifecycle (Although it needs more implementation maturity, number of contributors, and github :star: s...)

**Comment by AkihiroSuda** [comment]
Having slirp4netns and fuse-overlayfs in the same org sounds good :+1:, but my concern is that "containers" does not seem to have the official project name and the documentation about its governance. (well, that concern also applies to Rootless Containers though...)

**Comment by rhatdan** [comment]
If you want to help us generate one for Containers, we would be very willing to work with you on it.

**Comment by vbatts** [comment]
let's make proper governance for this containers org! that's what it was made for way back when.

**Comment by rhatdan** [comment]
@vbatts What do we need to do, to setup "proper governenance" of containers org?

**Comment by giuseppe** [comment]
I am closing this issue since containers has been already home for fuse-overlayfs until now
