### ISSUE TITLE
Alpine linux: "cannot read upper dir: Out of memory"

### ISSUE THREAD

**Issue by Disassembler0** [containers/fuse-overlayfs#174]
Any time fuse-overlayfs is executed under any user (root, non-root or user namespace) on Alpine linux host, it fails with 
```
fuse-overlayfs: cannot read upper dir: Out of memory
```
Enabling the debug output via `-d` or `-o debug` doesn't produce any additional output.

Uname (Alpine 3.11.3):
```
Linux alpine 5.4.12-1-virt #2-Alpine SMP Thu, 16 Jan 2020 12:53:54 UTC x86_64 Linux
```
Note that Alpine uses _musl libc_. Version of _libfuse3_ is 3.9.0.

**Steps to reproduce:**
```
apk add make autoconf automake fuse3 fuse3-dev gcc gettext git libc-dev linux-headers
git clone https://github.com/containers/fuse-overlayfs.git
cd fuse-overlayfs
./autogen.sh
./configure
make
make install
```
```
service fuse start
mkdir /mnt/upper /mnt/lower /mnt/work /mnt/merged
fuse-overlayfs -o lowerdir=/mnt/lower,upperdir=/mnt/upper,workdir=/mnt/work /mnt/merged
```

As a side note, I haven't been able to compile statically either, however I haven't invested much time into it as it seems that it's the reason why [Dockerfile.alpine](https://github.com/containers/fuse-overlayfs/blob/master/Dockerfile.alpine) is still empty.

**Comment by yaamai** [comment]
I had the same problem.

After some trial and error, "EINVAL" could be returned in some places, and the realpath + strcat combination seemed to trigger SEGV.

I created a patch(https://github.com/yaamai/fuse-overlayfs/commit/3733cfcb6936df685e62c5917493223aab700f5c), but I don't know this fix is correct or not...

**Comment by mpolanski** [comment]
I have exactly the same problem on Alpine Linux Edge as described by @Disassembler0. I've tested @yaamai's patch with Podman and it works fine.

**Comment by rhatdan** [comment]
@giuseppe Has this been fixed?

**Comment by giuseppe** [comment]
could you please open a PR?

Why does the EINVAL happen?  I'd prefer if it is fixed in `file_exists` and understand what flag causes it.

Also, please add a check for the result from `realloc`.  We can just fail with `error (EXIT_FAILURE, ..");` if it fails

**Comment by mgoltzsche** [comment]
Same problem here. Happens since >v0.4.1.
Is there any progress on this?

**Comment by giuseppe** [comment]
> After some trial and error, "EINVAL" could be returned in some places, and the realpath + strcat combination seemed to trigger SEGV.

have you had a chance to verify why `EINVAL` is returned?  Can we handle that in `file_exists`?

**Comment by mgoltzsche** [comment]
Apparently `AT_SYMLINK_NOFOLLOW` is a [glibc-specific](https://www.openwall.com/lists/musl/2014/09/25/1) `faccessat` flag.
fuse-overlayfs uses `faccessat` in [file_exists_at](https://github.com/containers/fuse-overlayfs/blob/50ab2c272c49c94334cf1fe2699522a93ca79570/utils.c#L106).
[musl's faccessat](https://github.com/ifduyue/musl/blob/b4b1e10364c8737a632be61582e05a8d3acf5690/src/unistd/faccessat.c#L26) doesn't support the flag directly but passes it to the kernel which may not support it.  

Alternatively `file_exists` could be implemented using `fstatat`:
```
struct stat buf;
return fstatat(dirfd, pathname, &buf, AT_SYMLINK_NOFOLLOW);
```
