### ISSUE TITLE
(deleted) files behavior on fuse-overlayfs

### ISSUE THREAD

**Issue by ITD27M01** [containers/fuse-overlayfs#175]
When files have deleted from Linux filesystems (including overlayfs) but held open by some processes they are disappearing from directory listing but stay present as file descriptors. You can use these files to write or read data by file descriptors (in the process which opens the file) but after close, you can forget about these files forever. Sometimes you can see the (deleted) mark in lsof output [2]

This behavior is used by tempfile python module to create temporary storage and this module is used by some useful applications such a pytest [3].

For example:

```
> python
Python 3.6.8 (default, Oct 11 2019, 15:04:54)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tempfile import TemporaryFile
>>> tmpfile = TemporaryFile()
>>> tmpfile_fd = tmpfile.fileno()
>>> tmpfile_fd
3
>>> import os
>>> os.readlink('/proc/self/fd/%d' % tmpfile.fileno())
'/tmp/#9587 (deleted)'
>>> tmpfile.seek(0)
0
>>> tmpfile.truncate()
0


> lsof | grep '/tmp/#9587'
python     2597                           root    3u      REG              252,1         0       9587 /tmp/#9587 (deleted)
```

When using the fuse-overlayfs I see the different behavior for some reason. The files disappear when they deleted and I cannot use tempfile nor pytest in such an environment:

```
(app-root) bash-4.4$ python
Python 3.6.8 (default, Oct 11 2019, 15:04:54)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tempfile import TemporaryFile
>>> tmpfile = TemporaryFile()
>>> tmpfile_fd = tmpfile.fileno()
>>> tmpfile_fd
3
>>> import os
>>> os.readlink('/proc/self/fd/%d' % tmpfile.fileno())
'/tmp/tmpx71fk293 (deleted)'
>>> tmpfile.seek(0)
0
>>> tmpfile.truncate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
>>>
```

As a result, I can't use rootless podman containers to test python applications. (As a workaround I can bind mount the /tmp filesystem to containers but this is not a solution for large environments)

[1] https://access.redhat.com/solutions/2316
[2] https://docs.python.org/3/library/tempfile.html
[3] https://github.com/pytest-dev/pytest/blob/master/src/_pytest/capture.py#L11

**Comment by giuseppe** [comment]
what fuse-overlayfs version are you using?

This issue seems to be already fixed upstream

**Comment by ITD27M01** [comment]
Hi @giuseppe , am using the rhel8 distribution and the following versions of packages:

```
[builder@srv8-lacmacis cloudcli]$ rpm -qa | grep fuse
fuse-overlayfs-0.4.1-1.module+el8.1.0+4081+b29780af.x86_64
fuse3-libs-3.2.1-12.el8.x86_64
fuse-libs-2.9.7-12.el8.x86_64
```

Could you tell me please the fixed version for informed communication with support?

**Comment by giuseppe** [comment]
is there are a bugzilla open to track this issue?

The easiest would probably be to rebase, I am working on some fixes right now that I'd also like to see in RHEL as soon as possible

**Comment by ITD27M01** [comment]
@giuseppe As soon as BZ will be created I will share its number.

**Comment by giuseppe** [comment]
since the issue doesn't exist upstream, I'll close it.

Let's followup on bugzilla for RHEL related stuff.
