### ISSUE TITLE
Error with locating libfuse3.so.3

### ISSUE THREAD

**Issue by josbake** [containers/fuse-overlayfs#18]
Receiving this error when trying to run the built fuse-overlayfs executable:

fuse-overlayfs: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory

I have no problem with libfuse on its own, so I'm guessing fuse-overlayfs just isn't locating the library correctly? Not sure what to make of it.

**Comment by rhatdan** [comment]
```
  locate libfuse3
/usr/lib64/libfuse3.so.3
/usr/lib64/libfuse3.so.3.2.3
```
Most likely looking here.

**Comment by josbake** [comment]
Got it; they were stuck in a nearby folder. Moved them around, and we are golden. Thanks.
