### ISSUE TITLE
NFS and subdirectories with many files

### ISSUE THREAD

**Issue by dhzavann** [containers/fuse-overlayfs#182]
I've been testing a bit by using an NFS mount as the lower layer, and local (initially empty) upper and workdirs. This seems to be a bit slow in some cases.

As one example, we have a directory which contains only around 15 entries; all directories. Each of these directories in turn have around 12 subdirectories (and so on). The initial listing of the parent directory containing only the 15 entries takes around 4 seconds in some informal testing.

The output from tcpdump seems to suggest that fuse-overlayfs is also recursing into the subdirectories. Querying the NFS mount directly does not result in the same type of recursion and is reasonably fast.

I'm guessing there's a good reason for doing this, but is there some flag or anything else that I'm missing or that could be added to skip this recursion?

**Comment by giuseppe** [comment]
That looks like something fuse-overlayys should not do, but it was never really tested on network file systems.

Are you using fuse-overlayfs as unprivileged user?  Could you give more information on how you are invoking it?

**Comment by dhzavann** [comment]
I'm using fuse-overlayfs as root in an unprivileged lxd container. I built fuse-overlayfs statically following the instructions a couple of hours ago.

I have tried mounting NFS both with nfusr inside the container, and with the kernel client bind mounted from the host through lxd. The issue manifests a bit differently between them and between runs (caching?), but I can trigger long waits in both cases.

An example session (slightly anonymized):

> \# NFS is mounted on /mnt/nfs
> time ls -lh /mnt/nfs/another/example/path | wc -l
> 10
>
> real	0m0.007s
> user	0m0.001s
> sys	0m0.006s
> 
> rm -rf /tmp/nfs
> mkdir -p /tmp/nfs/{upper,workdir,mount}
>
> sudo ./fuse-overlayfs -o uidmapping=33:1000:1,gidmapping=33:1000:1,lowerdir=/mnt/nfs,upperdir=/tmp/nfs/upper,workdir=/tmp/nfs/workdir /tmp/nfs/mount
> 
> time ls -lh /tmp/nfs/mount/another/example/path | wc -l
> 10
>
> real	0m27.898s
> user	0m0.006s
> sys	0m0.000s


The another/example/path contains only directories named after years (2012, 2013, ..). Below those are directories named after months (1-12). I can see in tcpdump expected queries, like: 

> NFS request xid 245309214 128 lookup fh Unknown/0100074D0001000000000000FF1E9CE6D01EA81E00000000000000000CBBF500 "2013"

However, after that I also see a bunch of requests for all the subdirectories, for example:

> 128 lookup fh Unknown/0100074D0001000000000000FF1E9CE6D01EA81E0000000000000000AEDCF500 "1"

**Comment by giuseppe** [comment]
I am trying locally but I don't see anything strange that could make that much difference.

Could you strace the fuse-overlayfs process before the `ls -lh` so we can see better what is happening?

You can run fuse-overlayfs normally, then from another terminal:

`$ strace -o /tmp/fuse-overlayfs.log -f -p $(pgrep fuse-overlayfs)`

Then run `ls -lh`, once it terminates, stop the strace process and please attach the `/tmp/fuse-overlayfs.log` file here.  Double check if it needs to be anonymized :-)

**Comment by giuseppe** [comment]
The first level must be read though to properly report the number of links for the directories.

so when you do `ls -lh foo/bar`, FUSE does a readdir_plus request, that also expects a stat for each entry.  To correctly report the number of links for each entry, there is need to look into the directory child nodes.

**Comment by dhzavann** [comment]
I tried again, but I used another path with a different structure. I also used only ls (aliased to ls --color=auto). This time I got:

> \# Nfs monted at /mnt/nfs
[fuse-overlayfs-fr3-a.log](https://github.com/containers/fuse-overlayfs/files/4199126/fuse-overlayfs-fr3-a.log)
>
> time ls /mnt/nfs/some/path | wc -l
> 11
>
> real	0m0.004s
> user	0m0.005s
> sys	0m0.000s
>
>
> rm -rf /tmp/nfs
> mkdir -p /tmp/nfs/{upper,workdir,mount}
>
> sudo ./fuse-overlayfs -o uidmapping=33:1000:1,gidmapping=33:1000:1,lowerdir=/mnt/nfs,upperdir=/tmp/nfs/upper,workdir=/tmp/nfs/workdir /tmp/nfs/mount
>
> \# strace started
>
> time ls /tmp/nfs/mount/some/path | wc -l
> 11
>
> real	0m42.014s
> user	0m0.002s
> sys	0m0.003s
>
> \# strace stopped

I attach the log, but I've applied sed to it :-) I've tried to keep the directory structure intact, but I replaced .wh.* with .wh.somefile and all other filenames with somefile. I hope it's still useful.

**Comment by dhzavann** [comment]
Considering this fixed with #282
