### ISSUE TITLE
help message is outdated

### ISSUE THREAD

**Issue by progrunner17** [containers/fuse-overlayfs#185]
According to the help message, `-d` option or  ` -o debug` option should enable the debug output, 
but it won't work while `--debug` option makes it.

I found the defect with my self-build fuse-overlayfs (commmit 8bba496f08787344ab45b36b0640d50b85edab78 ).

I'm sorry if the problem has already been fixed on the other commit or PR.

**Comment by rhatdan** [comment]
@progrunner17 interested in opening a PR to fix the help message?

**Comment by rhatdan** [comment]
I opened a PR.
