### ISSUE TITLE
touch -h fails to set the date for symlinks

### ISSUE THREAD

**Issue by progandy** [containers/fuse-overlayfs#204]
I was experimenting with reproducible builds in rootless containers and found fuse-overlayfs is unable to change the modification time of symlinks which is needed to set uniform timestamps to all files in the package. The kernel module does it without problems.

```bash
#!/bin/bash
# test-symlink-touch.sh 
# sudo test-symlink-touch.sh kernel
if [[ $1 == kernel ]]; then
mount="mount -t overlay"
umount=umount
else
mount=fuse-overlayfs
umount="fusermount -u"
fi
mkdir lower/ upper/ work/ merged/
$mount -o lowerdir=`pwd`/lower,upperdir=`pwd`/upper,workdir=`pwd`/work none `pwd`/merged
touch merged/afile
ln -s afile merged/alink
stat --format "mod: %y ;acc: %x" merged/alink
echo "Trying to set date to 2020-01-02"
touch -h -d "2020-01-02 12:13:14" merged/alink
stat --format "mod: %y ;acc: %x" merged/alink
$umount `pwd`/merged
rm -r lower upper work merged

```

Versions:
kernel: 5.4.33-2-lts (arch)
fuse-overlayfs 1.0.0-1
fuse3 3.9.1-1

**Comment by giuseppe** [comment]
thanks for the report.

Could you please try https://github.com/containers/fuse-overlayfs/pull/205 and see if it fixes the error you've seen?
