### ISSUE TITLE
Port to Buildroot

### ISSUE THREAD

**Issue by tianyuanhao** [containers/fuse-overlayfs#209]
I hope someone can port this to [Buildroot](https://buildroot.org/) as a package.

**Comment by rhatdan** [comment]
Go for it...

**Comment by tianyuanhao** [comment]
```Makefile
################################################################################
#
# fuse-overlayfs
#
################################################################################

FUSE_OVERLAYFS_VERSION = 1.0.0
FUSE_OVERLAYFS_SITE = $(call github,containers,fuse-overlayfs,v$(FUSE_OVERLAYFS_VERSION))
FUSE_OVERLAYFS_DEPENDENCIES = libfuse3
FUSE_OVERLAYFS_LICENSE = GPL-3.0
FUSE_OVERLAYFS_LICENSE_FILES = COPYING

FUSE_OVERLAYFS_AUTORECONF = YES

$(eval $(autotools-package))
```

I will not maintain it, so I hope someone is willing to submit it to Buildroot.

**Comment by tianyuanhao** [comment]
@paralin

Hey, Christian. Would you like to maintain this package for Buildroot? Docker now supports [fuse-overlayfs](https://github.com/docker/engine/tree/master/daemon/graphdriver/fuse-overlayfs). So I hope to use it in Buildroot. Because you can mount fuse-overlayfs on top of overlayfs, when you use overlayfs as root.

**Comment by paralin** [comment]
This is pretty cool. I have added a task to my short-term backlog to make a package for it.

**Comment by rhatdan** [comment]
Any progress?

**Comment by paralin** [comment]
On it

**Comment by paralin** [comment]
I've submitted the package to Buildroot upstream: https://patchwork.ozlabs.org/project/buildroot/patch/20200618191839.398771-1-christian@paral.in/

The commit is available on GitHub here: https://github.com/paralin/buildroot/commit/3777c12898af90241a582a499e38a75780d9f0aa

The package builds cleanly as a straightforward autotools/autogen package with a libfuse3 dependency.

**Comment by tianyuanhao** [comment]
@paralin Thank you very much.

@rhatdan I will close this issue when it is merged into the upstream.

**Comment by paralin** [comment]
Merged to buildroot master.
