### ISSUE TITLE
hanging in the merged directory

### ISSUE THREAD

**Issue by vbatts** [containers/fuse-overlayfs#21]
carrying over https://github.com/containers/fuse-overlayfs/pull/19#issuecomment-428916937

### Reproducer:
in one terminal:
```shell
[vbatts@getdown] {master} ~$ mkdir /tmp/{upper,workdir,merged}
[vbatts@getdown] {master} ~$ fuse-overlayfs -f -o lowerdir=$HOME,upperdir=/tmp/upper,workdir=/tmp/workdir /tmp/merged
UID=unchanged
GID=unchanged
UPPERDIR=/tmp/upper
WORKDIR=/tmp/workdir
LOWERDIR=/home/vbatts
MOUNTPOINT=/tmp/merged
```

in the other terminal:
```shell
cd /tmp/merged
```

### Description

> on the cd /tmp/merged, since I happen to have a large enough $HOME folder and a $PS1 that looks for a .git folder, with this fix now cd /tmp/merged causes fuse-overlayfs to freeze when my $PS1 scans for git changes. I can't crtl+c, only killall -9 fuse-overlayfs and umount /tmp/merged to cleanup.

### More info:
```shell
[vbatts@getdown] {master} ~$ du -sh ~/
75G     /home/vbatts/
[vbatts@getdown] {master} ~$ find ~/ -type d | wc -l
177465
[vbatts@getdown] {master} ~$ echo $PS1
\[\033[0;94m\][\u@\h]\[\033[0m\]$(git branch &>/dev/null;\ if [ $? -eq 0 ]; then \ echo "$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; \ if [ "$?" -eq "0" ]; then \ # @4 - Clean repository - nothing to commit echo "\[\033[0;32m\]"$(__git_ps1 " (%s)"); \ else \ # @5 - Changes to working tree echo "\[\033[0;91m\]"$(__git_ps1 " {%s}"); \ fi) \[\033[1;94m\]\w\[\033[0m\]\$ "; \ else \ # @2 - Prompt when not in GIT repo echo " \[\033[0;94m\]\w\[\033[0m\]\$ "; \ fi)
[vbatts@getdown] {master} ~$ git ls-files | wc -l
243
```

Strace https://vbatts.fedorapeople.org/fuse-overlayfs_issue21.0.dump
(the command looked like `sudo strace -o dump -f ./fuse-overlayfs -f -o lowerdir=$HOME,upperdir=/tmp/upper,workdir=/tmp/workdir /tmp/merged` since strace without sudo got an EPERM on `mount`)

### my work  around
Setting `export PS1="$> "` allows me to `cd` into that directory, so it's something in the git status doing a directory traversal that is freezing up the fuse-overlayfs.

**Comment by giuseppe** [comment]
for a simpler reproducer, you can just `mkfifo foo` in the lower directory, then fuse-overlayfs will hang when trying to access it
