### ISSUE TITLE
[Errno 2] No such file or directory after some unknown steps

### ISSUE THREAD

**Issue by alxchk** [containers/fuse-overlayfs#213]
I have strange issue with fuse-overlayfs, which is perfectly reproducible, but I can't build any minimal sample for that.

I have very fun setup, with python 2.7 in wine in podman :)
Issue looks like this. 

During container creation, I install python packages using pip. In case I start this container (with already installed packages) once again, some random files began to disappear.

```
Installing collected packages: six, cython, pyjnius
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Rolling back uninstall of six
  Moving to c:\python27\lib\site-packages\six-1.15.0-py2.7.egg-info
   from c:\python27\lib\site-packages\~ix-1.15.0-py2.7.egg-info
  Moving to c:\python27\lib\site-packages\six.py
   from c:\users\root\temp\pip-uninstall-ua5iy4\six.py
  Moving to c:\python27\lib\site-packages\six.pyc
   from c:\users\root\temp\pip-uninstall-ua5iy4\six.pyc
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Python27\\Lib\\site-packages\\six-1.15.0.dist-info\\LICENSE'
```

**Comment by giuseppe** [comment]
can you please provide more information?  What version of fuse-overlayfs are you using?

What steps do you perform before hitting the issue?

**Comment by alxchk** [comment]
I'm using latest from git. I observed this behaviour since the first usage of fuse-overlayfs. I'm using it since 0.7.7. 

As I said, I can't make minimal example of this. I will try to make something small, but problem usually arise in quite big project

**Comment by alxchk** [comment]
Okay. Looks like these actions reproduces the issue in some form. Please note, I'm not sure which actions exactly triggers this. So this is a fat example.. 

( podman with fuse-overlayfs )

```
mkdir test; cd test; cat >script.sh << __EOF__
#!/bin/sh

PACKAGES_BUILD="netifaces msgpack-python u-msgpack-python construct bcrypt watchdog dukpy impacket zeroconf==0.19.1"
PACKAGES_BUILD="\$PACKAGES_BUILD pycryptodomex pycryptodome cryptography pyOpenSSL paramiko"

PACKAGES="rsa pefile rsa netaddr win_inet_pton netaddr pypiwin32 poster win_inet_pton dnslib"
PACKAGES="\$PACKAGES pyaudio https://github.com/secdev/scapy/archive/master.zip colorama pyaudio"
PACKAGES="\$PACKAGES https://github.com/alxchk/pypykatz/archive/master.zip"
PACKAGES="\$PACKAGES https://github.com/warner/python-ed25519/archive/master.zip"
PACKAGES="\$PACKAGES https://github.com/alxchk/tinyec/archive/master.zip"
PACKAGES="\$PACKAGES https://github.com/alxchk/urllib-auth/archive/master.zip"
PACKAGES="\$PACKAGES https://github.com/alxchk/winkerberos/archive/master.zip"
PACKAGES="\$PACKAGES https://github.com/alxchk/pyuv/archive/v1.x.zip"
PACKAGES="\$PACKAGES adodbapi idna http_parser pyodbc wmi==1.4.9"

echo "HELLO THERE"

for PYTHON in \$PYTHON32 \$PYTHON64; do
    \$PYTHON -m pip install -q --upgrade pip
    \$PYTHON -m pip install -q --upgrade setuptools cython
    \$PYTHON -m pip install -q --upgrade pynacl
    \$PYTHON -m pip install -q --upgrade --no-binary :all: \$PACKAGES_BUILD

    NO_JAVA=1 \
        \$PYTHON -m pip install -q --upgrade --force-reinstall \
        https://github.com/alxchk/pyjnius/archive/master.zip

    \$PYTHON -m pip install -q --upgrade --force-reinstall \
        https://github.com/alxchk/scandir/archive/master.zip

    \$PYTHON -m pip install -q --upgrade \$PACKAGES
done

echo "DONE"
__EOF__
```

```
podman run --name test -v `pwd`:/build/workspace/project  \
   -it alxchk/tc-windows bash script.sh
```

And then several times

```
podman start -a test
```

The issue will looks like this:

```
ERROR: Could not install packages due to an EnvironmentError: 
[Errno 2] No such file or directory: 'C:\\Python27\\Lib\\site-packages\\six-1.15.0.dist-info\\LICENSE'
```

**Comment by giuseppe** [comment]
thanks, this is definitely going to help me.

**Comment by giuseppe** [comment]
still debugging as I've not yet figured out what is going on.

Have you had a chance to run it as root using native overlay instead of fuse-overlayfs?  Does it work correctly?  I am trying it right now as well

**Comment by alxchk** [comment]
I used this in docker without any issues. Do you mean podman + vfs = overlayfs?

**Comment by giuseppe** [comment]
https://github.com/containers/fuse-overlayfs/pull/214 seems to fix the issue.  I am  running more tests right now to make sure it is all we need

**Comment by alxchk** [comment]
Thanks for the fix. This was very annoying bug

**Comment by alxchk** [comment]
Well, it turns out, that some kind of these things still exists. And now they looks like

```
ERROR: Could not install packages due to an EnvironmentError: [Error 183] File already exists
```

**Comment by giuseppe** [comment]
are you using fuse-overlayfs 1.0.2?

**Comment by alxchk** [comment]
I'm using the one from git/master (06/18/2020).

```
# fuse-overlayfs --version
fuse-overlayfs: version 1.1.0
FUSE library version 3.9.2
using FUSE kernel interface version 7.31
fusermount3 version: 3.9.2
```

Will try most recent one today.

**Comment by giuseppe** [comment]
not sure there is any fix for this issue since 1.1.0.

Do you have a reproducer?  Same steps as above?

**Comment by alxchk** [comment]
This is the same setup. But i'm not sure that small subset is enough. Previously the problem arised every time, now it's from time to time. Also, after 1-2 "failures", there is "recovery". I.e. if previously bug was each time after first run, and looks a bit different. Now it's like:
1st run - ok
2nd run - ok
3rd run - fail
4rd run - ok
5rd run - ok
6th run - fail
7nth run - fail
8nth run - fail
9nth run - ok

Problems still in this python - wine combo.

Maybe there are some other atomic apis? Also, If you'll provide the way how to collect data for debug, I may try to get this from live project.

**Comment by giuseppe** [comment]
I am running it in a loop and I've not encountered the issue even once with the current fuse-overlayfs master.

**Comment by alxchk** [comment]
Right now I have these issues several times even from first run, which looks like:
```
ERROR: Could not install packages due to an EnvironmentError: [Error 183] File already exists
```

Also I made modification to the example:

```
\$PYTHON -c 'import pyuv' || exit 1"
```

before `done `

This modification will not cover all cases, when this error matters, just only one for one particular module.

And run in cycle:
```
while :; do podman kill test; podman stop test; podman start -a test; done
```

There will be messages like these:
```
ERROR: Could not install packages due to an EnvironmentError: [Error 183] File already exists

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyuv\__init__.py", line 3, in <module>
    from ._version import __version__
ImportError: cannot import name __version__
```

Or just

```
ERROR: Could not install packages due to an EnvironmentError: [Error 183] File already exists
```
