### ISSUE TITLE
v1.1.1 tag is signed by github

### ISSUE THREAD

**Issue by Foxboron** [containers/fuse-overlayfs#221]
With the `v1.1.1` tag both the commit and the tag is signed by the github GPG key, and not by the previous release key.

It would be great if the signing key would be consistent, and not by github, so it would be possible to attest some authenticity to the fuse-overlay releases.

**Comment by giuseppe** [comment]
@AkihiroSuda is it possible to add or replace the signature for the release?

**Comment by AkihiroSuda** [comment]
git tag -s ?

**Comment by giuseppe** [comment]
I thought the issue was for the release.

@Foxboron I see the v.1.1.1 tag having the same signature as previous ones:

```
$ git show v1.1.1
tag v1.1.1
Tagger: Giuseppe Scrivano <gscrivan@redhat.com>
Date:   Sat Jun 20 21:45:17 2020 +0200

v1.1.1
-----BEGIN PGP SIGNATURE-----

iQEzBAABCAAdFiEEAn871YWUyhgbtexQ5HMPl/YChu0FAl7uZ1EACgkQ5HMPl/YC
hu0RHwgAkXCZCICoj7QdmrT3XvG2B2BewczvkDtCWOZ0P+f5bTBKtk0ZwIqiinxW
23w7qyItIBzcnWzBryePG6rGQnM5cGIXFR0NDtMI3xs4GscR6EukDmYtx94QtFl8
t0yMCxeqGRs0iZVOfkcdozXXMCFB7NAUHZnsoAnnuB7qDGw90/UabGQ8QeBWAb9k
+eh1UJMKvUod89t0FJt/naPYtxEBp6t6aTkT6G/PY8q8vGV2p5RB71V/c4qAErcO
n7NRrvN+uMzSMPQRh4+50siXfoFlGntmW5X50lbrgta8eZ7lfuMOYCGUOQjTLuMZ
CwXfWMdnR8CPp59SEPSJf0AyG/bjiw==
=jD5z
-----END PGP SIGNATURE-----
```


do you see something different?

**Comment by Foxboron** [comment]
Ah, apologies. It's only the merge commit itself. We usually don't use the tags directly in Arch packages to prevent retagging attacks on the repository.

I'll build it with the signed tag for this release. And as a sidenote It would also be nice with signed tarballs :)
