### ISSUE TITLE
Got "Out of Memory" after running rootless container for a while

### ISSUE THREAD

**Issue by bear0330** [containers/fuse-overlayfs#222]
Hi, 

I have run/build many rootless containers on my machine, but after a while, I always got this message on journalctl 
kernel: Out of memory: Killed process 42806 (fuse-overlayfs) total-vm:494664kB, anon-rss:220096kB, file-rss:0kB, shmem-rss:0kB, UID:1001

Then, my httpd process in container will crash, container will shut down.

I have no idea about this problem.

podman info:
[root@jupiter letsencrypt]# podman info
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: a2b11288060ebd7abd20e0b4eb1a834bbf0aec3e'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 121274368
  MemTotal: 3961708544
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8192
  SwapTotal: 536866816
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: jupiter.nuwainfo.com
  kernel: 4.18.0-193.6.3.el8_2.x86_64
  os: linux
  rootless: false
  uptime: 70h 14m 23.43s (Approximately 2.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

CentOS 8.2 4G ram

Thanks.

**Comment by giuseppe** [comment]
what version of fuse-overlayfs are you using?

Do you have a reproducer for the issue?  What container are you running?

**Comment by giuseppe** [comment]
Patch included here: https://github.com/containers/fuse-overlayfs/pull/223
