### ISSUE TITLE
Latest release 1.1.2: fuse-overlayfs --version shows the wrong version

### ISSUE THREAD

**Issue by manics** [containers/fuse-overlayfs#224]
`fuse-overlayfs --version` shows the wrong version:
```
$ wget https://github.com/containers/fuse-overlayfs/releases/download/v1.1.2/fuse-overlayfs-x86_64

$ chmod +x fuse-overlayfs-x86_64 

$ ./fuse-overlayfs-x86_64 --version
fuse-overlayfs: version 1.1.0
FUSE library version 3.4.1
using FUSE kernel interface version 7.27
fusermount3 version: 3.9.1

```
Looks like this wasn't updated for the `1.1.1` or `1.1.2` releases:
https://github.com/containers/fuse-overlayfs/blob/fb8b3e03ca3945d7363a2290abf4ac012c4676ee/configure.ac#L2

**Comment by giuseppe** [comment]
thanks for the report but it is too late to address it now ;(  I'll keep the issue open so I won't repeat the mistake for the next release

**Comment by bear0330** [comment]
The same issue even now is 1.2.0
