### ISSUE TITLE
allow colons in paths for lowerdir to be escaped

### ISSUE THREAD

**Issue by tdyas** [containers/fuse-overlayfs#227]
I have a lowerdir path that has a colon in it. It would be nice if the [`read_dirs` function](https://github.com/containers/fuse-overlayfs/blob/800011be8fdffa35f674c984beaeff69d2a5a9f0/main.c#L1591-L1719) allowed the colon to be escaped (for example, as `\:`) such that it was not interpreted as the separator between paths when escaped.

**Comment by giuseppe** [comment]
how does the kernel escape the directories for overlay?  Are directories with `:` in the name allowed?

**Comment by tdyas** [comment]
> how does the kernel escape the directories for overlay? Are directories with `:` in the name allowed?

The kernel `overlayfs` allows colons to be escaped with a preceding backslash. See https://github.com/torvalds/linux/blob/e2c46b5762c616c249201688d3b9846627f78d2c/fs/overlayfs/super.c#L893-L894.

**Comment by giuseppe** [comment]
> > 
> 
> The kernel `overlayfs` allows colons to be escaped with a preceding backslash. See https://github.com/torvalds/linux/blob/e2c46b5762c616c249201688d3b9846627f78d2c/fs/overlayfs/super.c#L893-L894.

thanks for letting me know.

Would you like to open a PR? :-)

**Comment by tdyas** [comment]
> Would you like to open a PR? :-)

Will do.

**Comment by giuseppe** [comment]
@tdyas are you still interested in having this feature?

**Comment by tdyas** [comment]
> @tdyas are you still interested in having this feature?

Not any more. I haven't had any time to work on this request, so going to close for now.

**Comment by peesock** [comment]
In addition to commas and colons, it seems backslashes also need escaping (for *all* characters besides comma?), which is the same behavior as the kernel FS. To avoid this pain, shouldn't filepaths be their own argument on the CLI? Something like:
```
fuse-overlayfs --lower "$HOME/path" --lower "$HOME/path2" --upper ...
```
Or if cloning normal `mount` behavior is desired, are commas, colons, and backslashes the only things needed to escape? (Not that colons can be escaped yet)
