### ISSUE TITLE
fuse-overlayfs very memory hungry

### ISSUE THREAD

**Issue by bear0330** [containers/fuse-overlayfs#238]
Hi, 

I have about 9 containers run python app on a 4G ram machine. After couple weeks later, fuse-overlayfs process for every container will eat about 10~15% memory. It seems like slowly increased. 
So after few couple weeks (maybe 2 weeks) I need to reboot or restart all my containers to free memory.
Even my python apps doesn't use that lot of memory, I think there might some memory leak in fuse-overlayfs or it just very memory hungry process.

Thanks.

**Comment by giuseppe** [comment]
when you see the memory usage so high, could you try running as root `# sync; echo 3 > /proc/sys/vm/drop_caches`?

It might be caused by the cache that is kept in memory when there is no memory pressure, it is not handled by fuse-overlayfs but the kernel decides when it must be freed.

**Comment by bear0330** [comment]
Thank you, but actually OOM will work if I don't reboot my machine or restart container to make memory usage down. If it is just about cache, kernel will free it under memory pressure situation right? 
I will see many fuse-overlayfs process use more than 10% of memory after my containers has been killed by oom.

**Comment by giuseppe** [comment]
I've opened a PR to solve a potential leak, and be more aggressive on releasing inodes.

**Comment by kawhicurry** [comment]
I meet the same problem with `fuse-overlayfs version: 0.7.2`. The `buffer+cache memory` slowly increase and after they reached the top, `used memory` increase rapidly until it consume all the memory. I check the `top` and found `fuse-overlayfs` consume over 50% of the memory. I haven't test the latest version but it might work.
