### ISSUE TITLE
Typo in debug log 

### ISSUE THREAD

**Issue by progrunner17** [containers/fuse-overlayfs#247]
There are several code for debug like following.
```c
fprintf (stderr, "ovl_open(ino=%" PRIu64 "s)\n", ino);
```

The output of this code was like following. 
```
ovl_open(ino=12345s)
```

The "s" seems strange for me. 

Is this just a mistake? 
Or is there any reason for this?

If it is just a mistake, I'm ready for open PR.

**Comment by giuseppe** [comment]
it is a mistake

**Comment by giuseppe** [comment]
since the PR was merged, I am closing the issue
