### ISSUE TITLE
Page cache sharing in fuse-overlayfs

### ISSUE THREAD

**Issue by sectorsize512** [containers/fuse-overlayfs#254]
Kernel version of overlay2 supports supports page cache sharing. I.e., when multiple containers access same file, they share a single page cache entry for that file. Does fuse-overlayfs has the same property? Thank you!

**Comment by giuseppe** [comment]
the cache maintained by libfuse for each file is not shared.  Each read/write will ultimately end up to the same underlying files and the page cache for those is shared.

**Comment by sectorsize512** [comment]
Thank you, Giuseppe, that's the impression I also got. By libfuse cache you probably mean the in-kernel page cache for fuse? And, if I remember correctly, it is quite limited in size (I think the kernel limits fuse's bdi limit for page cache for safety reasons). Do you know if that's (still) the case? Thanks!

(My reasoning here: even though fuse-overlayfs is duplicating data at fuse's page cache level, the duplication is limited since the size of the fuse's page cache is constrained).

**Comment by giuseppe** [comment]
I am closing this issue since that is out of control for fuse-overlayfs, and the kernel doesn't offer anything at the moment to address it.
