### ISSUE TITLE
inplace sed fails with permission error  

### ISSUE THREAD

**Issue by sgotand** [containers/fuse-overlayfs#265]
I encounter an error like this.
```bash
$ head -n2 /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
$ fuse-overlayfs -V
fuse-overlayfs: version 1.3
FUSE library version 3.10.1
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.1
$ mkdir mnt lo up work
$ echo hello > lo/hello.txt
$ fuse-overlayfs -o workdir=work,upperdir=up,lowerdir=lo ./mnt
$ sed -i 's/hello/HELLO/' ./mnt/hello.txt
sed: preserving permissions for ‘./mnt/sedYeWmNl’: Permission denied
$
```
With strace, I found out that sed failed at fchown.
```
99011 openat(AT_FDCWD, "/home/vagrant/sed_test/mnt/sedhPumiV", O_RDWR|O_CREAT|O_EXCL, 0600) = 4
99011 umask(002)                        = 0700
99011 fcntl(4, F_GETFL)                 = 0x8002 (flags O_RDWR|O_LARGEFILE)
99011 fstat(3, {st_mode=S_IFREG|0777, st_size=6, ...}) = 0
99011 read(3, "HELLO\n", 4096)          = 6
99011 fstat(4, {st_mode=S_IFREG|000, st_size=0, ...}) = 0
99011 read(3, "", 4096)                 = 0
99011 fchown(4, 1000, 1000)             = -1 EACCES (Permission denied)
99011 fchown(4, -1, 1000)               = -1 EACCES (Permission denied)
```
With further investigation, this failure seems from this line. 
https://github.com/containers/fuse-overlayfs/blob/master/main.c#L3878-L3884

Although I tried to fix this bug, but it was too hard for me, 
because I have no idea why permission error occurs with same user
nor why `fuse_file_info *fi` is set NULL and this line is executed.

**Comment by giuseppe** [comment]
fuse-overlayfs is really meant to be used from a user namespace.  While it works without a user namespace, there can be some issues not encountered when running with capabilities, e.g. when accessing directories.

Could you show what is the permission mask for "mnt lo up work" ?

**Comment by progrunner17** [comment]
Thank you for your explanation。.

Originally, their mask is 0002, but this error also occured even when I changed the mask to 0000.

**Comment by giuseppe** [comment]
> Originally, their mask is 0002, but this error also occurred even when I changed the mask to 0000.

that is too restrictive.  Could you try with `700` or `755`?

`0002` looks more like a umask (what privileges are taken away when a new file is created).

**Comment by progrunner17** [comment]
Sorry, I misread your message. 
As you have pointed out, `0002` and `0000` are the result of `umask`.
The actual permission of the directories are `775`(when umask is 0002) or `777`(when umask is 0000),
because the directories are used just after created with `mkdir`.

**Comment by progrunner17** [comment]
With additional investigation, I find a new fact.

`fchown`ing a file with permission 000 in non-fuse-overlayfs mount point succeed, 
but `fchown`ing a file with permission 000 failed under fuse-overlayfs failed with EACCES.

**Comment by rhatdan** [comment]
@sgotand Are you still seeing this?  @giuseppe any idea what is going on?

**Comment by giuseppe** [comment]
>  @giuseppe any idea what is going on?

these kind of issues happen when fuse-overlayfs is not running inside a user namespace and it lacks the DAC_OVERRIDE capability.  This use case is not relevant for us, but I am fine to review a patch if someone is willing to work on one.

**Comment by sgotand** [comment]
Thank you both, but I 'not interested in this issue anymore.
