### ISSUE TITLE
"mv: replace 'blah', overriding mode 0007?" even though 'blah' does not exist

### ISSUE THREAD

**Issue by kwshi** [containers/fuse-overlayfs#273]
**Description**

> **EDIT/TLDR**: I have narrowed down the issue to a minimal, reproducible example; [Containerfiles demonstrating the bug can be found here](https://github.com/kwshi/buildah-bug-reports/tree/main/opam-help/minimal).  Skip to [this comment](https://github.com/containers/buildah/issues/2951#issuecomment-770247464) for specific steps and observations; the following stuff is what I originally wrote while trying to narrow down the problem, but it may not be super interesting to you.

Honestly, I don't know where to file the issue, since it's so obscure and specific.  But this bug doesn't show up when I use Docker, which leads me to believe it _may_ be a buildah-specific issue.  But I have otherwise no idea what's going on.  Here goes...

While trying to build a container with [opam](https://opam.ocaml.org) and some other OCaml packages installed, I received the following error message from opam while it was attempting to download packages:
```
+ /usr/sbin/mv "/home/opam/.opam/download-cache/sha256/e2/e2c4e8230f7c96236503fd75f22bdbc263639971bf104509e446855ded35ae1e.tmp.part" "/home/opam/.opam/download-cache/sha256/e2/e2c4e8230f7c96236503fd75f22bdbc263639971bf104509e446855ded35ae1e.tmp"
- /usr/sbin/mv: replace '/home/opam/.opam/download-cache/sha256/e2/e2c4e8230f7c96236503fd75f22bdbc263639971bf104509e446855ded35ae1e.tmp', overriding mode 0007 (------rwx)?
```
However, closer inspection reveals that the file `mv` thinks it's _replacing_, namely `/home/opam/****ae1e.tmp`, doesn't actually exist--so it doesn't make sense to me why it raises this warning at all.  My best guess is that it maybe has something to do with bugs in the filesystem implementation that is causing `mv` to think it needs to override a file when there actually isn't.

Building the same containerfile with Docker proceeds fine, without any errors, leading me to further believe this issue seems to lie somewhere in buildah/podman.

**Steps to reproduce the issue:**

1. I wrote a [Containerfile](https://github.com/kwshi/buildah-bug-reports/blob/main/opam-help/Containerfile) that reproduces the issue for me when attempting to build with `buildah bud .` or `podman build .` (both reproduce the issue for me).
   
   I haven't tried this with other OS's because I'm not super familiar with their ecosystems, but if anyone else wants to try to reproduce on other OS's (so that we can eliminate the cause being the `voidlinux` base), here are some specific features to consider reproducing:

  - opam version 2.07
  - `dune-configurator` needs to be the first and only opam package installed (I know, right??).  It seems that, depending on the particular order in which I install packages, this bug may or may not appear.  Installing absolutely nothing before `dune-configurator` seems to be one way to reproduce it reliably for me.
  - On Docker only, `opam init` requires `--disable-sandboxing` because of some kernel/namespace/permissions business.  I don't really understand what that means, but for some reason on buildah `--disable-sandboxing` is not required (provided you first install the `bubblewrap`/`bwrap` program).
  - Enable extra-verbose logging `-vvv` so you can see the commands opam tries to run; otherwise, it'll just look like the download hangs, and you don't see the actual "mv: y/n?" prompt that is causing the hang.

2. After a _long_ compile time (thanks, opam), opam should finally attempt to install `dune-configurator`, log a `curl` command, followed by an `mv` command, and then hang on the `/usr/sbin/mv: replace ...?` prompt.

3. To confirm that the file in question actually doesn't exist:

   a. Delete the last line from the Containerfile so that every command before but not including `opam install -vvvy dune-configurator` runs and build the container (alternatively, scroll up the log output from the previous build attempt and find the image hash of the layer right before the `opam install -vvvy dune-configurator` command).

   b. `podman run -it --rm <image>`, and manually run `opam install -vvvy dune-configurator` from the interactive shell.  When presented with the `mv` prompt, hit ctrl-z and run `bg` to send the opam process to the background; meanwhile, `cd` to the folder mentioned in the prompt (e.g. `/home/opam/.opam/download-cache/sha256/e2`) and `ls -la`.  You should see that there is a `<blahblah>.tmp.part` and a `<blahblah>`, but _no_ `<blahblah>.tmp` as mentioned by `mv`.

**Output of `rpm -q buildah` or `apt list buildah`:**

N/A, since my host system is Void Linux, but the analogous command is `xbps-query -S buildah`, I think:

```
architecture: x86_64
filename-sha256: ff159fe96edba7ec270e01dac2057f32fac5f6987f9f3e0d2d254d2587817e40
filename-size: 13MB
homepage: https://github.com/containers/buildah
install-date: 2020-11-19 19:25 UTC
installed_size: 28MB
license: Apache-2.0
maintainer: Cameron Nemo <cnemo@tutanota.com>
metafile-sha256: 4687075e1a7cbf8f5704cf6bc596ed8f3cbe447ea0f06132ab3319e545fbde80
pkgname: buildah
pkgver: buildah-1.16.2_1
repository: https://alpha.us.repo.voidlinux.org/current
run_depends:
	runc>=0
	containers.image>=0
	glibc>=2.29_1
	libgpgme>=1.12.0_2
	libassuan>=2.0.1_1
	libgpg-error>=1.6_1
	device-mapper>=2.02.110_1
shlib-requires:
	libpthread.so.0
	libgpgme.so.11
	libassuan.so.0
	libgpg-error.so.0
	libdevmapper.so.1.02
	libc.so.6
short_desc: Dockerfile compatible OCI image building tool
source-revisions: buildah:7bf843e361
state: installed
```

**Output of `buildah version`:**

```
Version:         1.16.2
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.5.2
Git Commit:
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

**Output of `uname -a`:**

```
Linux vic 5.8.18_1 containers/buildah#1 SMP Sun Nov 1 14:25:13 UTC 2020 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

Nonexistent, since I was using buildah rootless--the relevant `storage.conf` there was `~/.config/containers/storage.conf`, pasted below:
```toml
[storage]
driver = "overlay"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
```

But that raises a good point--I have not yet tried to build this as root, and I wonder whether the results would be different if I did.

---

For reference, here is a complete log of the build: https://github.com/kwshi/buildah-bug-reports/blob/main/opam-help/fail-log

I'll also file an issue under the opam project to see if they have any input on what might be going on and how to more reliably reproduce this error.

**Comment by giuseppe** [comment]
> The sequence of commands to run _as a non-root user_ (as root, `mv` doesn't bother prompting to override permissions):
> 
> ```shell
> touch a b
> chmod 6 a
> mv a x # rename 'a' to something else, so 'a' should no longer exist
> ls -la # to make absolutely sure 'a' is gone
> mv b a # should not have problems, since 'a' is gone
> # yet `mv` somehow decides to prompt anyway
> ```

I am not able to reproduce the issue using this reproducer.  I've tried both on 5.10.10-200.fc33.x86_64 and on 4.18.0-240.10.1.el8_3.x86_64.

What is the version of fuse-overlayfs you are using?

**Comment by giuseppe** [comment]
I was able to reproduce: https://github.com/containers/fuse-overlayfs/pull/274

Another issue happening because of the dev whiteout files that unprivileged users can create on newer kernels
