### ISSUE TITLE
RFE: chaining mounts similarly to the overlayfs

### ISSUE THREAD

**Issue by mskarbek** [containers/fuse-overlayfs#275]
`overlayfs` lets using other `overlayfs` mount as a lower dir and changes in that mount are propagated to the second mount. Unfortunately, that is not true with `fuse-ovelrayfs` mounts.

**Comment by giuseppe** [comment]
is that a documented behavior?

AFAIK, the assumption done by overlay is that the lower layers are not modified.

**Comment by giuseppe** [comment]
closing as there was no feedback, please reopen if there is further information
