### ISSUE TITLE
How to install latest version on ubuntu 20.10

### ISSUE THREAD

**Issue by mo-saeed** [containers/fuse-overlayfs#283]
Hello,

Is there any package in ubuntu with the latest version and is there any instructions on how to install it?

Thanks

**Comment by AkihiroSuda** [comment]
You can get static binaries here, not dpkg though: https://github.com/containers/fuse-overlayfs/releases/tag/v1.4.0

**Comment by giuseppe** [comment]
agreed, the binary version is probably the easiest way to get it.

Alternatively you could try https://software.opensuse.org//download.html?project=devel%3Akubic%3Alibcontainers%3Aunstable&package=fuse-overlayfs
