### ISSUE TITLE
Numerical result out of range (error: -34) returned by mkdir when fuser-overlayfs runs over cvmfs

### ISSUE THREAD

**Issue by sectorsize512** [containers/fuse-overlayfs#284]
Buongiorno! I'm trying to run fuse-overlayfs over cvmfs (aka CernVM-FS):

```
fuse-overlayfs -f --debug -olowerdir=/cvmfs/vasilyobj15.repo.name/mycentos/,upperdir=/home/vass/upper,workdir=/home/vass/work /home/vass/merged/
```

Then in a separate terminal I run mkdir (this `secrets` directory is typically created by podman during container creation):

```
mkdir /home/vass/merged/run/secrets
mkdir: cannot create directory ‘/home/vass/merged/run/secrets’: Numerical result out of range
```

fuse-overlayfs shows the follwoing debug messages:

```
unique: 16, opcode: LOOKUP (1), nodeid: 21661632, insize: 48, pid: 26031
ovl_lookup(parent=21661632, name=secrets)
   unique: 16, error: -2 (No such file or directory), outsize: 16
unique: 17, opcode: MKDIR (9), nodeid: 21661632, insize: 56, pid: 26031
ovl_mkdir(ino=21661632, name=secrets, mode=511)
   unique: 17, error: -34 (Numerical result out of range), outsize: 16
```

Any suggestions on how to debug this further? Thank you!

In case it matters: 

`
fuse-overlayfs --version
fuse-overlayfs: version 0.4.1
FUSE library version 3.2.1
using FUSE kernel interface version 7.26
`

**Comment by giuseppe** [comment]
Hi!

Could you strace fuse-overlayfs while it is failing and attach the output here?

From another terminal:

`strace -v -s 4000 -p $FUSE_OVERLAYS_PID`

and then attempt the mkdir operation that causes the error above?

**Comment by sectorsize512** [comment]
Thanks, Giuseppe! Here is what I got:

```
...
openat(3, "run", O_RDONLY|O_NONBLOCK)   = 9
....
fgetxattr(9, "user.external_timeout", "10", 256) = 2
fsetxattr(10, "user.external_timeout", "10", 2, 0) = 0
fgetxattr(9, "user.pubkeys", 0xf36190, 256) = -1 ERANGE (Numerical result out of range)
...
```

Interestingly many preceding `fgetxattrs()` on fd 9 succeed, but this specific one fails... 🤔

**Comment by shenghaoyang** [comment]
Did you leave the magic CVMFS xattrs enabled? Some of them can be quite large (especially the key xattr) and fuse-overlayfs doesn't resize the xattr buffer properly, resulting in that ERANGE.

**Comment by giuseppe** [comment]
> fgetxattr(9, "user.pubkeys", 0xf36190, 256) = -1 ERANGE (Numerical result out of range)

thanks!

So it seems there is not much fuse-overlayfs can do since cvmfs just refuses to write the xattr.

One possible workaround is to disable xattrs for the fuse-overlayfs mount (with the `noxattrs=1` mount option)

**Comment by sectorsize512** [comment]
Thank you both @giuseppe  and @shenghaoyang! It turned out that CVMFS indeed defaults to exposing numerous "magic" (synthetic) extended attributes, and the value of the attribute `user.pubkeys` is larger than 256Bytes - the limit that fuse-overlayfs assumes in `fgetxattr()`. As a result `fgetxattr()` fails with `ERANGE` and this is what fuse-overlayfs returns to the `mkdir`.

The workaround for me for setting `CVMFS_HIDE_MAGIC_XATTRS=true` in CVMFS config.

I'm not closing the issue since it seems like it is something that could be fixed in fuse-overlayfs, but feel free to close as project authorities.

**Comment by giuseppe** [comment]
thanks, I've opened a PR to address it in fuse-overlayfs: https://github.com/containers/fuse-overlayfs/pull/286
