### ISSUE TITLE
ensure HEAD version is ahead of latest tag / follow semver

### ISSUE THREAD

**Issue by lsm5** [containers/fuse-overlayfs#294]
@rhatdan @giuseppe so right now, HEAD is at version `1.5`. The latest released tag is `v1.5.0`.
Can we have HEAD ahead of the latest tag? Maybe `v1.5.1-dev` or `v1.6.0-dev` or anything ahead of latest tag?

This would make it convenient for package builds and ensuring that rawhide is always ahead of fedora release branches.

**Comment by giuseppe** [comment]
sure, we can tag the new version in the git repo: https://github.com/containers/fuse-overlayfs/pull/295
