### ISSUE TITLE
"Operation not permitted" when using -o uid/gidmapping

### ISSUE THREAD

**Issue by LukasRupprecht** [containers/fuse-overlayfs#299]
I am running into "Operation not permitted" errors when trying to modify data on a fuse-overlay file system, which was mounted using `-o uidmapping=... -o gidmapping=...`.

A simple scenario to reproduce the issue is below. In the example, everything in the upper and lower layers is owned by `root` and mapped to my user in `fuse-overlayfs` so it would be mapped back to `root` in a user namespace (I am running this outside of a user namespace to prepare a root file system for `podman --rootfs`).

```bash
$ ls -l
total 0
drwxr-xr-x 2 root   root   22 Jun 18 17:22 lower
drwxr-xr-x 2 lukasr lukasr  6 Jun 10 10:35 merged
drwxrwxrwx 2 root   root    6 Jun 18 17:51 upper
drwxr-xr-x 3 lukasr lukasr 18 Jun 18 17:51 work
$ ls -l lower/
total 0
-rw-r--r-- 1 root root 0 Jun 18 17:22 testfile
$ fuse-overlayfs -o uidmapping=0:$(id -u):1 -o gidmapping=0:$(id -g):1 \
  -olowerdir=lower,upperdir=upper,workdir=work merged
$ ls -l
total 0
drwxr-xr-x 2 root   root   22 Jun 18 17:22 lower
drwxrwxrwx 2 lukasr lukasr  6 Jun 18 17:51 merged
drwxrwxrwx 2 root   root    6 Jun 18 17:51 upper
drwxr-xr-x 3 lukasr lukasr 18 Jun 18 17:51 work
$ ls -l merged/
total 0
-rw-r--r-- 1 lukasr lukasr 0 Jun 18 17:22 testfile
$ echo "Hello World" >merged/testfile2
-bash: merged/testfile2: Operation not permitted
```

Interestingly, if I mount the overlay file system with `-o squash_to_uid=$(id -u) -o squash_to_gid=$(id -g)`, I can write to `merged` without problems. From looking at the code, it seems `find_mapping` (in `main.c`) resolves the uid differently for the two different mapping options. However, given that they are both mapping `root` to `lukasr`, I would have assumed that they are equivalent?

In the above example, I could just resort to using `squash_to_uid/gid`. However, in my actual use case, my lower layer has files owned by different users and I want to preserve the original uids. Hence, I'd need to specify the mapping through `-o uid/gidmapping`. Is there a way to achieve that without running into permission problems?

**Comment by giuseppe** [comment]
fuse-overlayfs itself needs to run in a user namespace (unless you are running as root) in order to gain access to different UIDs/GIDs.

Are the commands above running in a user namespace?

If you are preparing the environment for Podman, I'd suggest to first enter the `podman unshare` environment, as that user+mount namespace is the one Podman uses for creating rootless containers and you can mount your own file system there (that can be accessed and used by `--rootfs`

**Comment by LukasRupprecht** [comment]
I did not run the above commands in a user namespace. It works once I mount both my root file system and the corresponding fuse-overlayfs from within a user namespace (entered through `podman unshare`).

Thanks for the help!
