### ISSUE TITLE
Fuse-overlayfs produces filesystems considered corrupted by kernel overlayfs

### ISSUE THREAD

**Issue by sipsma** [containers/fuse-overlayfs#306]
This was first noticed by @hinshun, who is using fuse-overlayfs to create layers for containers which can later be mounted by the kernel overlay implementation. This was tested using the v1.6 x86 fuse-overlayfs binary on a host running kernel 5.8.12.

We expected that layers created by fuse-overlayfs would always be considered valid by the kernel implementation, but we've found a case where fuse-overlayfs creates a layer where a directory that is marked as opaque also contains a whiteout file, which the kernel doesn't understand and results in files showing up in listdir results but giving errors when stat'd directly.

Here's a reproducer, with the script running from a new empty directory as root:
```
root@host:~/fuse-ovl# cat repro.sh
#!/bin/sh

set -x

mkdir -p tmp/lower/a/b tmp/upper tmp/work tmp/mnt
fuse-overlayfs -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt

rm -rf tmp/mnt/a
mkdir -p tmp/mnt/a/b
mv tmp/mnt/a/b tmp/mnt/b
ls -la tmp/mnt/*

umount tmp/mnt
ls -la tmp/upper/*

mount ovl -t overlay -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt
ls -la tmp/mnt/*
umount tmp/mnt





root@host:~/fuse-ovl# ./repro.sh
+ mkdir -p tmp/lower/a/b tmp/upper tmp/work tmp/mnt
+ fuse-overlayfs -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt
+ rm -rf tmp/mnt/a
+ mkdir -p tmp/mnt/a/b
+ mv tmp/mnt/a/b tmp/mnt/b
+ ls -la tmp/mnt/a tmp/mnt/b
tmp/mnt/a:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 4 root root 4096 Jun 28 12:11 ..

tmp/mnt/b:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 4 root root 4096 Jun 28 12:11 ..
+ umount tmp/mnt
+ ls -la tmp/upper/a tmp/upper/b
tmp/upper/a:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 4 root root 4096 Jun 28 12:11 ..
c--------- 1 root root 0, 0 Jun 28 12:11 b
crwx------ 1 root root 0, 0 Jun 28 12:11 .wh..opq
-rwx------ 1 root root    0 Jun 28 12:11 .wh..wh..opq

tmp/upper/b:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 4 root root 4096 Jun 28 12:11 ..
-rwx------ 1 root root    0 Jun 28 12:11 .wh..wh..opq
+ mount ovl -t overlay -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt
+ ls -la tmp/mnt/a tmp/mnt/b
tmp/mnt/a:
ls: cannot access 'tmp/mnt/a/b': No such file or directory
ls: cannot access 'tmp/mnt/a/.wh..opq': No such file or directory
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 1 root root 4096 Jun 28 12:11 ..
c????????? ? ?    ?       ?            ? b
c????????? ? ?    ?       ?            ? .wh..opq
-rwx------ 1 root root    0 Jun 28 12:11 .wh..wh..opq

tmp/mnt/b:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 12:11 .
drwxr-xr-x 1 root root 4096 Jun 28 12:11 ..
-rwx------ 1 root root    0 Jun 28 12:11 .wh..wh..opq
+ umount tmp/mnt
```

As you can see, `upper/a` is an opaque directory but also contains a whiteout file. Fuse-overlayfs is fine with this, but once you mount the same layers using kernel overlay the whiteout, `mnt/a/b`, incorrectly shows up in the listdir and you also get stat errors on it.

To be clear, the existence of the `.wh..opq` and `.wh..wh..opq` files is not important, you can also manually remove them before mounting with the kernel overlay (as would be done by, for example, containerd's fs applier used during image unpacking) and get the same problem because the kernel only cares about opaque xattrs of the containing dir, which are also set.

This arguably could be considered a bug in the kernel's implementation, but I believe they don't handle it well because they seem to always prevent a whiteout file from appearing in a directory marked as opaque. This can be seen by a similar script that runs using just kernel overlay:
```
root@host:~/ovl# cat repro.sh
#!/bin/sh

set -x

mkdir -p tmp/lower/a/b tmp/upper tmp/work tmp/mnt
mount ovl -t overlay -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt

rm -rf tmp/mnt/a
mkdir -p tmp/mnt/a/b
mv tmp/mnt/a/b tmp/mnt/b
ls -la tmp/mnt/*

umount tmp/mnt
ls -la tmp/upper/*





root@host:~/ovl# ./repro.sh
+ mkdir -p tmp/lower/a/b tmp/upper tmp/work tmp/mnt
+ mount ovl -t overlay -o lowerdir=tmp/lower,upperdir=tmp/upper,workdir=tmp/work tmp/mnt
+ rm -rf tmp/mnt/a
+ mkdir -p tmp/mnt/a/b
+ mv tmp/mnt/a/b tmp/mnt/b
+ ls -la tmp/mnt/a tmp/mnt/b
tmp/mnt/a:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 11:51 .
drwxr-xr-x 1 root root 4096 Jun 28 11:51 ..

tmp/mnt/b:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 11:51 .
drwxr-xr-x 1 root root 4096 Jun 28 11:51 ..
+ umount tmp/mnt
+ ls -la tmp/upper/a tmp/upper/b
tmp/upper/a:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 11:51 .
drwxr-xr-x 4 root root 4096 Jun 28 11:51 ..

tmp/upper/b:
total 8
drwxr-xr-x 2 root root 4096 Jun 28 11:51 .
drwxr-xr-x 4 root root 4096 Jun 28 11:51 ..
```

Whether or not this is something the kernel should handle better, I feel it would make sense for fuse-overlayfs to also not create whiteout files in opaque directories as they aren't needed for functionality and doing so would increase compatibility with the kernel implementation.

**Comment by giuseppe** [comment]
I am fine to address this difference in fuse-overlayfs if it helps your use case, but I am afraid there can be also other incompatibilities between the layers created by fuse-overlayfs and what the kernel expects.

fuse-overlayfs uses the device whiteout files only on newer kernels where they are supported also for unprivileged users, on older kernels it uses the `.wh.` whiteout format (I still regret this choice, but at that time it made easier the integration with existing tools).

Tools using containers/storage use native overlay for unprivileged users only with a completely empty storage.  If there are images/containers created with fuse-overlayfs we keep using fuse-overlayfs to avoid such kind of incompatibilities.

**Comment by giuseppe** [comment]
would the following patch work for you?

```diff
$ git diff
diff --git a/main.c b/main.c
index 1701a56..ff5b88b 100644
--- a/main.c
+++ b/main.c
@@ -655,20 +655,21 @@ set_fd_origin (int fd, const char *origin)
 static int
 set_fd_opaque (int fd)
 {
-  cleanup_close int opq_whiteout_fd = -1;
   int ret;
 
   ret = fsetxattr (fd, PRIVILEGED_OPAQUE_XATTR, "y", 1, 0);
   if (ret < 0)
     {
-      if (errno == ENOTSUP)
-        goto create_opq_whiteout;
-      if (errno != EPERM || (fsetxattr (fd, OPAQUE_XATTR, "y", 1, 0) < 0 && errno != ENOTSUP))
-          return -1;
+      ret = fsetxattr (fd, OPAQUE_XATTR, "y", 1, 0);
+      if (ret < 0 && errno == ENOTSUP)
+        {
+          cleanup_close int opq_whiteout_fd = -1;
+
+          opq_whiteout_fd = TEMP_FAILURE_RETRY (safe_openat (fd, OPAQUE_WHITEOUT, O_CREAT|O_WRONLY|O_NONBLOCK, 0700));
+          return (opq_whiteout_fd >= 0 || ret == 0) ? 0 : -1;
+        }
     }
- create_opq_whiteout:
-  opq_whiteout_fd = TEMP_FAILURE_RETRY (safe_openat (fd, OPAQUE_WHITEOUT, O_CREAT|O_WRONLY|O_NONBLOCK, 0700));
-  return (opq_whiteout_fd >= 0 || ret == 0) ? 0 : -1;
+  return ret;
 }
```

**Comment by sipsma** [comment]
> I am fine to address this difference in fuse-overlayfs if it helps your use case, but I am afraid there can be also other incompatibilities between the layers created by fuse-overlayfs and what the kernel expects.

Makes sense. I suppose all these various incompatibilities can and should also be checked by each container runtime and fixed when pulling+unpacking images onto a native overlay filesystem, even if you make an update for this issue. Many of these incompatibilities, such as the different whiteout formats you mentioned, are already handled for the most part today (at least in containerd, which I'm most familiar with).

This "whiteout in opaque dir" case isn't though and felt like it was in a grey-area tending towards bug since whiteouts should theoretically never be needed in opaque dirs, so I wanted to let you know about it and still appreciate any fixes you make. Either way, I will also see if I can update containerd to correct it on image unpack and maybe reach out to the kernel-side maintainers to see if they think it's worth changing the behavior on their end too.

**Comment by sipsma** [comment]
@giuseppe the patch resulted in the .wh. opaque files not showing up, but the opaque xattr was still set and the whiteout for the deleted dir (upper/a/b in the reproducer) was still there, which is the one that causes problems. I was imagining the fix to be leaving the directory as opaque but just not including whiteouts under any opaque dirs.

I tried some other changes and found this one worked as I expected:
```
diff --git a/main.c b/main.c
index e89c51a..e993001 100644
--- a/main.c
+++ b/main.c
@@ -1065,6 +1065,7 @@ hide_node (struct ovl_data *lo, struct ovl_node *node, bool unlink_src)
             needs_whiteout = true;
         }

+      needs_whiteout = needs_whiteout && is_directory_opaque(get_upper_layer(lo), node->parent->path) < 1;
       if (needs_whiteout)
         {
           /* If the atomic rename+mknod failed, then fallback into doing it in two steps.  */
```

Not familiar with the codebase at all so I doubt that's the best way to do it, but that's the gist.

**Comment by giuseppe** [comment]
@sipsma the patch LGTM, and I am fine to merge it.

Would you mind to open a PR?
