### ISSUE TITLE
Unnecessary whiteout file when renaming.

### ISSUE THREAD

**Issue by vexingcodes** [containers/fuse-overlayfs#327]
When a file is renamed, a whiteout file must be created in the upper directory if any lower directory contains the source. If the lower directories do _not_ contain the source then a whiteout file is not necessary, but it does not functionally harm anything to create one. In the Linux kernel OverlayFS implementation, if a file is renamed and the source is not in a lower directory, no whiteout file is created; however, the fuse-overlayfs implementation does create one.

This discrepancy doesn't appear to break anything functionally, but it does interfere with reproducibility when running commands which rename randomly-named files that only ever exist in the upper directory. For example, using `sed --in-place` to modify a file that is only in the upper directory can result in a randomly-named whiteout file being created in the upper directory because the way sed implements in-place editing is to create a new, randomly-named file and rename it into place atomically.

Here is a short bash script to demonstrate this discrepancy:
```bash
#!/bin/bash
set -euo pipefail

[[ ${EUID} -ne 0 ]] && echo "Must run as root!" && exit 1

# Show useful system information.
uname -r
fuse-overlayfs --version
echo

function run_test {
  # Work in a temporary directory.
  TEST_DIR="$(mktemp --directory)"
  cd "${TEST_DIR}"

  # Set up the test using the desired method.
  mkdir lower upper work merged
  if [[ "${1}" == "overlayfs" ]]; then
    mount -t overlay overlay -o lowerdir=lower,upperdir=upper,workdir=work merged
  else
    fuse-overlayfs -o lowerdir=lower,upperdir=upper,workdir=work merged
  fi

  # Perform the test.
  echo "test" > merged/test
  sed --in-place 's/test/TEST/' merged/test

  # Report the results.
  echo "METHOD=${1}"
  ls -Al upper
  echo

  # Clean up.
  umount merged
  rm --recursive --force "${TEST_DIR}"
}

run_test overlayfs
run_test fuse-overlayfs
```

The following is the output of that script on my system:
```
5.14.14-arch1-1
fuse-overlayfs: version 1.7.1
FUSE library version 3.10.5
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.5

METHOD=overlayfs
total 4
-rw-r--r-- 1 root root 5 Oct 23 22:34 test

METHOD=fuse-overlayfs
total 4
c--------- 1 root root 0, 0 Oct 23 22:34 sedKDg08c
-rw-r--r-- 1 root root    5 Oct 23 22:34 test
```

Here fuse-overlayfs has a `sedKDg08c` whiteout file, but Linux OverlayFS has no whiteout file. Note, unnecessary whiteout files are _not_ created when _removing_ files that only ever existed in the upper directory, this appears to apply only to renaming.

**Comment by Tuupertunut** [comment]
I can confirm this. Every time a file is renamed, an unnecessary whiteout is left. This causes a whiteout spam when doing lots of sed in-place edits.

**Comment by Kawashima-Azumi** [comment]
> I can confirm this. Every time a file is renamed, an unnecessary whiteout is left. This causes a whiteout spam when doing lots of sed in-place edits.

Confirmed & I think rsync can trigger more massive whiteout spams than sed.
