### ISSUE TITLE
EIO for ioctl FS_IOC_GETFLAGS

### ISSUE THREAD

**Issue by dbnicholson** [containers/fuse-overlayfs#330]
Not sure if this is expected behavior, a fuse-overlayfs issue or a fuse issue, but I get `EIO` when using `lsattr` after it calls `ioctl` with `FS_IOC_GETFLAGS`. From the caller:

```
$ lsattr -d d
lsattr: Input/output error While reading flags on d
```

Here's the strace output from fuse-overlayfs:

```
openat2(3, ".", {flags=O_RDONLY|O_NONBLOCK, resolve=RESOLVE_IN_ROOT}, 24) = 8
ioctl(8, FS_IOC_GETFLAGS, 0x7ffd6d1d1bc0) = 0
writev(5, [{iov_base="(\0\0\0\0\0\0\0\204\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\27\0\0\0\0\0\0\0", iov_len=8}], 3) = -1 EINVAL (Invalid argument)
dup(2)                                  = 9
fcntl(9, F_GETFL)                       = 0x80002 (flags O_RDWR|O_CLOEXEC)
fstat(9, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
write(9, "fuse: writing device: Invalid argument\n", 39fuse: writing device: Invalid argument
) = 39
close(9)                                = 0
close(8)                                = 0
```

What I don't get is the actual `ioctl` call succeeds, but then `writev` gets `EINVAL` writing to `/dev/fuse`. This is running unprivileged from the root user namespace, but I originally hit it in a podman container. This is with fuse-overlayfs 1.7.1, fuse 3.10.3 and linux 5.13.0.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/fuse-overlayfs/pull/335
