### ISSUE TITLE
Image corruption when using fuse-overlayfs instead of overlayfs inside a Docker container

### ISSUE THREAD

**Issue by mh21** [containers/fuse-overlayfs#333]
When generating images for [Dockerfile](https://github.com/containers/fuse-overlayfs/files/7861838/Dockerfile.txt) via buildah running in a Docker container, a file is corrupted when using fuse-overlayfs. This is not the case when using overlayfs (without fuse).

Steps to reproduce:

- spin up a small VM (e.g. AWS/`t2.small`, RHOSP/`g.standard.small`) with FC34 or FC35 *connected to the Red Hat intranet* (FC35 on AWS us-east-1 is `ami-08b4ee602f76bff79`, from <https://alt.fedoraproject.org/cloud/>)
- setup the VM via
  ```bash
  sudo dnf install -y moby-engine
  sudo systemctl enable docker
  sudo systemctl start docker
  ```
- to verify the build is working via overlayfs on the upstream buildah/stable image, run 

  ```bash
  sudo docker run --rm --privileged quay.io/buildah/stable:latest buildah bud --storage-opt mount_program= -f https://gitlab.com/cki-project/containers/-/raw/d3f2634e066b2eab0a4a9d84ec295b4a2543b475/Dockerfile
  ```
  - logs FC34: [logs-overlayfs-fc34-working.log](https://github.com/containers/fuse-overlayfs/files/7861774/logs-overlayfs-fc34-working.log)
  - logs FC35: [logs-overlayfs-fc35-working.log](https://github.com/containers/fuse-overlayfs/files/7861775/logs-overlayfs-fc35-working.log)

- trying to build the Dockerfile with fuse-overlayfs instead fails with a checksum error 

  ```bash
  sudo docker run --rm --privileged quay.io/buildah/stable:latest buildah bud -f https://gitlab.com/cki-project/containers/-/raw/d3f2634e066b2eab0a4a9d84ec295b4a2543b475/Dockerfile
  ```
  - logs FC34: [logs-fuse-overlayfs-fc34-broken.log](https://github.com/containers/fuse-overlayfs/files/7861758/logs-fuse-overlayfs-fc34-broken.log)
  - logs FC35: [logs-fuse-overlayfs-fc35-broken.log](https://github.com/containers/fuse-overlayfs/files/7861760/logs-fuse-overlayfs-fc35-broken.log)

We have only observed that with the `/usr/lib64/python3.6/site-packages/libcomps/_libpycomps.so` file on our ubi8/rhel8 images.

This file is present in the ubi8 image (checksum in `before.sha256`), and gets updated to a newer version during `dnf update` (checksum in `after.sha256`). During one of the following RUN steps, the file reverts to the original version, which `rpm --verify` detects. It varies at exactly what RUN step that happens. Sometimes, this reversion is even incomplete for a while, i.e. only a part of the file reverts to the original contents.

In the Docker container, /var/lib/containers is a separate volume, with either `ext4` (FC34 host, and Docker using the `overlayfs2` driver), or `btrfs` (FC35 host, and Docker using the `btrfs` driver). 

We have two RHOSP VMs running (FC34/FC35) that can be used to reproduce the problem, let me know on RH IRC `#kernelci` if you want to have an SSH key added.

**Comment by giuseppe** [comment]
does the error reproduce if you use podman instead of docker?

**Comment by giuseppe** [comment]
I've run the command successfully on F35 using Podman:

```
STEP 58/58: RUN sha256sum -c after.sha256
/usr/lib64/python3.6/site-packages/libcomps/_libpycomps.so: OK
```

how often does it reproduce?

**Comment by mh21** [comment]
> how often does it reproduce?
Every time.

**Comment by mh21** [comment]
On the FC34 machine,

```bash
sudo podman run --rm --privileged quay.io/buildah/stable:latest buildah bud -f https://gitlab.com/cki-project/containers/-/raw/d3f2634e066b2eab0a4a9d84ec295b4a2543b475/Dockerfile
```

fails with the same error: 
[logs-fuse-overlayfs-fc34-podman-broken.log](https://github.com/containers/fuse-overlayfs/files/7862750/logs-fuse-overlayfs-fc34-podman-broken.log)

**Comment by giuseppe** [comment]
can you reproduce it only on the F34 machine?

Is it fully updated?

I could reproduce it on a fresh installed F34 VM, but once I've run `yum upgrade` it, I am not able anymore to reproduce it.

It could be caused by a different kernel version

**Comment by mh21** [comment]
It also reproduces with podman on FC35.

**Comment by mh21** [comment]
> Is it fully updated?

jfyi, even if a kernel update would help, these container image builds are happening in dynamic workers spawned for GitLab jobs, so those EC2 machines are kinda locked to the kernel in the ami 😕.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/fuse-overlayfs/pull/335
