### ISSUE TITLE
"Operation not supported" (EOPNOTSUPP) when accessing files owned by other users on underlying fs without ACL support

### ISSUE THREAD

**Issue by cdauth** [containers/fuse-overlayfs#336]
I'm running a Docker daemon using fuse-overlayfs as its storage driver, with the file system where the Docker storage resides not supporting ACLs. Not supporting ACLs manifests itself in for example `chacl -l testfile` showing “Operation not supported” (strace output: `getxattr("testfile", "system.posix_acl_access", 0x7ffe12b3c1a0, 132) = -1 EOPNOTSUPP (Operation not supported)`). In my particular case, the underlying file system is an older version of gocryptfs, but you should be able to replicate this for example by mounting an ext4 file system with `-o noacl`.

Inside a Docker container on such a system, when I try to read a file owned by another user, even if I am root and clearly have permission to read the file, I get an error “Not supported” (strace output: `open("test", O_RDONLY|O_LARGEFILE) = -1 EOPNOTSUPP (Not supported)`).

Now I don't know much about fuse-overlayfs itself, but I simply looked at the command that Docker is running in the background and replicated it with the `-f -d` flags to find out more details. Here is the output:
```
[root@test ~]# fuse-overlayfs -d -f -o lowerdir=/srv/docker/fuse-overlayfs/l/K4QHHZOMHZTC5OT47XJAWLOXS5:/srv/docker/fuse-overlayfs/l/F6VBBDQJIUSU2N2HYYE27AEELS,upperdir=/srv/docker/fuse-overlayfs/829360eb0c14de0ef81e851b29211e5f9af5b838a39e80878512d67ac9264527/diff,workdir=/srv/docker/fuse-overlayfs/829360eb0c14de0ef81e851b29211e5f9af5b838a39e80878512d67ac9264527/work /mnt &
[root@test ~]# touch /mnt/test
unique: 32, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1954
ovl_getattr(ino=1)
   unique: 32, success, outsize: 120
unique: 34, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 1954
ovl_lookup(parent=1, name=test)
   unique: 34, success, outsize: 144
unique: 36, opcode: CREATE (35), nodeid: 1, insize: 61, pid: 1954
ovl_create(parent=1, name=test)
   unique: 36, success, outsize: 160
unique: 38, opcode: FLUSH (25), nodeid: 94319634560272, insize: 64, pid: 1954
   unique: 38, error: -38 (Function not implemented), outsize: 16
unique: 40, opcode: SETATTR (4), nodeid: 94319634560272, insize: 128, pid: 1954
ovl_setattr(ino=94319634560272, to_set=1200)
   unique: 40, success, outsize: 120
unique: 42, opcode: RELEASE (18), nodeid: 94319634560272, insize: 64, pid: 0
ovl_release(ino=94319634560272)
   unique: 42, success, outsize: 16
[root@test ~]# chown nobody:nobody /mnt/test
unique: 44, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1955
ovl_getattr(ino=1)
   unique: 44, success, outsize: 120
unique: 46, opcode: GETATTR (3), nodeid: 94319634560272, insize: 56, pid: 1955
ovl_getattr(ino=94319634560272)
   unique: 46, success, outsize: 120
unique: 48, opcode: GETXATTR (22), nodeid: 94319634560272, insize: 68, pid: 1955
ovl_getxattr(ino=94319634560272, name=security.capability, size=0)
   unique: 48, error: -95 (Operation not supported), outsize: 16
unique: 50, opcode: GETATTR (3), nodeid: 94319634560272, insize: 56, pid: 1955
ovl_getattr(ino=94319634560272)
   unique: 50, success, outsize: 120
unique: 52, opcode: SETATTR (4), nodeid: 94319634560272, insize: 128, pid: 1955
ovl_setattr(ino=94319634560272, to_set=1030)
   unique: 52, success, outsize: 120
[root@test ~]# cat /mnt/test
unique: 54, opcode: GETXATTR (22), nodeid: 94319634560272, insize: 72, pid: 1956
ovl_getxattr(ino=94319634560272, name=system.posix_acl_access, size=4096)
   unique: 54, error: -95 (Operation not supported), outsize: 16
cat: /mnt/test: Operation not supported
```

Now I'm not an expert on this topic, but it seems to me that fuse-overlayfs should also work on underlying file systems that don't support ACLs, as long as I am not trying to use ACLs within fuse-overlayfs.

**Comment by giuseppe** [comment]
Could you try passing the `noacl` mount option to fuse-overlays?

**Comment by giuseppe** [comment]
I am closing as I've got no answer on my previous question.  Please reopen it that didn't work for you
