### ISSUE TITLE
SIGTERM not handled

### ISSUE THREAD

**Issue by splitice** [containers/fuse-overlayfs#341]
When launched in foreground mode SIGTERM is not handled. It should be a graceful shutdown.

```
kill -sSIGTERM  68
```

FYI This is the same signal that kubernetes uses. So anyone using fuse-overlayfs kubernetes has to wait on the terminationgraceperiod.

**Comment by splitice** [comment]
Strange I tried it again (directly after the previous) and it worked.

I wonder if something is disabling the signal handling at some point, or some call is blocking but not interruptable. I'll continue to investigate.

**Comment by giuseppe** [comment]
if you kill the fuse-overlayfs process you will leave a mount around.

The clean way to terminate fuse-overlayfs is to use `fusermount -u /$MNTPATH`
