### ISSUE TITLE
sed inplace edit removes all permissions on NFS filesystem

### ISSUE THREAD

**Issue by Tuupertunut** [containers/fuse-overlayfs#348]
Related to #265 
Possibly related to #327

**OS:** Ubuntu 20.04, kernel 5.13.0-40-generic
**fuse-overlayfs version:** 1.8.2
**Fuse library version:** 3.4.1
**NFS version:** 4.1
**sed version:** 4.7

**How to reproduce:**

Run this code on an NFS file system

```bash
unshare --mount --user --map-root-user bash -c '
    mkdir lower upper work mount
    fuse-overlayfs -o squash_to_root -o lowerdir=lower,upperdir=upper,workdir=work mount
    echo abcde > mount/testfile
    sed -i s/a/b/ mount/testfile
    fusermount -uz mount
'
```

**Actual behavior:**

It will fail with a message like
`sed: preserving permissions for ‘mount/sedZUa3s8’: Permission denied`

The contents of the directory `upper` will look like this
```
$ ls -al upper
total 8
drwx------ 2 myuser mygroup 4096 May  3 20:18 .
drwxr-xr-x 6 myuser mygroup 4096 May  3 20:18 ..
---------- 1 myuser mygroup    6 May  3 20:18 testfile
-rwx------ 1 myuser mygroup    0 May  3 20:18 .wh.sedZUa3s8
```

The file `testfile` has lost all of its permissions. There is also an unnecessary whiteout file left (issue #327). The content of `testfile` has changed from abcde to bbcde so the sed command has done its job.

**Expected behavior:**

Repeating the same code on an ext4 filesystem

It succeeds without errors.

The contents of the directory `upper` will look like this
```
$ ls -al upper
total 12
drwx------ 2 myuser mygroup 4096 May  3 20:39 .
drwx------ 6 myuser mygroup 4096 May  3 20:39 ..
c--------- 1 myuser mygroup 0, 0 May  3 20:39 sedEwVgW3
-rw------- 1 myuser mygroup    6 May  3 20:39 testfile
```

The file `testfile` has the expected permissions and the expected content.

**Comment by Kawashima-Azumi** [comment]
Not seeing this permission denied error with fuse-overlayfs-1.8.2 with both low and upper dirs from nfs3. Mount options are
`fuse-overlayfs -o lowerdir=/mnt/lower,upperdir=/mnt/upper/data,workdir=/mnt/upper/work,timeout=0,noacl,noxattrs,clone_fd,static_nlink,threaded=1,fast_ino=1,noatime union-rw`
However, sed does leave over a character device file.

**Comment by Tuupertunut** [comment]
@Kawashima-Azumi Could you try running it with the same mount options that I tried? It might be the `-o squash_to_root` to blame.

Another thing: Did you say a character device file? On my NFS filesystems whiteouts are always in the `.wh.*` form and not character devices. That could be relevant, since on ext4 filesystems whiteouts are character devices and this bug does not exist.

**Comment by Kawashima-Azumi** [comment]
> It might be the -o `squash_to_root` to blame.

Same behavior.

> Another thing: Did you say a character device file?

Yes.

> On my NFS filesystems whiteouts are always in the .wh.* form and not character devices. That could be relevant, since on ext4 filesystems whiteouts are character devices and this bug does not exist.

Not sure if related:
[https://github.com/kahing/goofys/issues/175#issuecomment-751452512](url)

(Didn't check that closely, though. No time to debug this in the next few days.)

**Comment by ollpu** [comment]
Seems that this has been fixed in sed v4.8 (fuse-overlayfs is mentioned specifically):
https://github.com/mirror/sed/commit/f69b085d3e7011ad6fa1dcf1473879a961fa1605

An interesting combination of incompatibilities:
- In general, it is possible to create a file with `000` permissions and while keeping the same file descriptor open, change its permissions. sed did this prior to the bugfix.
- FUSE/fuse-overlayfs translate these permission changes to ones where a new file descriptor is opened for the file.
- It shouldn't be possible to `open(O_RDONLY)` on a file with `000` permissions, but it happens to work on native ext4. NFS and likely other file systems don't allow this, so the file doesn't get proper permissions before it is moved on top of the original file.

So, `fuse-overlayfs` could try to be more pedantic and perform the `chown/chmod` without opening a file descriptor, but this specific issue with sed has already been fixed.

**Comment by Tuupertunut** [comment]
Okay, so the bug has nothing to do with whiteout files.

Based on ollpu's explanation and my debugging, the bug seems to be both in sed and fuse-overlayfs (and maybe even ext4).

**The sed side:**
sed 4.7 is creating a file with permissions 000 and only afterwards setting its permissions properly. sed 4.8 fixes this (although the latest sed on Ubuntu 20.04 will stay at 4.7 🙁).

**The fuse-overlayfs side:**
fuse-overlayfs is translating the original syscall that always works with 000 permissions

- `fchmod(*known file descriptor*, 0700)`

to ones that don't work on NFS filesystems with 000 permissions

- throw away known file descriptor
- `new_fd = openat(file, O_RDONLY)` < fails here with permission denied
- `fchmod(new_fd, 0700)`

This does not affect sed 4.8 anymore, but I found that this bug is still triggered if I try to use chmod directly. I will make a new bug report for that.

**Comment by Tuupertunut** [comment]
Continued in #349
