### ISSUE TITLE
Cannot chmod file with no permissions on NFS filesystem

### ISSUE THREAD

**Issue by Tuupertunut** [containers/fuse-overlayfs#349]
Continues from #348 

**OS:** Ubuntu 20.04, kernel 5.13.0-44-generic
**fuse-overlayfs version:** latest commit from main dedd8410ed0dd52150c98a9d666b875388f5395e
**Fuse library version:** 3.9.0
**NFS version:** 4.1
**chmod version:** 8.30

**How to reproduce:**

Run this code on an NFS file system

```bash
unshare --mount --user --map-root-user bash -c '
    mkdir lower upper work mount
    fuse-overlayfs -o squash_to_root -o lowerdir=lower,upperdir=upper,workdir=work mount
    touch mount/testfile
    chmod a-rwx mount/testfile
    chmod u+rw mount/testfile
    fusermount -uz mount
'
```

**Actual behavior:**

The second chmod command fails with an error message
`chmod: changing permissions of 'mount/testfile': Permission denied`

The file `upper/testfile` has no permissions afterwards
`---------- 1 myuser mygroup    0 May 25 03:36 testfile`

**Expected behavior:**

Repeating the same code on an ext4 filesystem displays no error messages.

The file `upper/testfile` has the expected permissions
`-rw------- 1 myuser mygroup    0 May 25 04:31 testfile`

Also running the code without fuse-overlayfs on NFS works as expected

```bash
touch testfile
chmod a-rwx testfile
chmod u+rw testfile
```

**Comment by Tuupertunut** [comment]
**Why this happens:**

The cause of this bug is that the fuse-overlayfs implementation/translation of `chmodat` syscall actually requires more permissions than the original syscall.

`chmod` uses the syscall

- `chmodat(dirfd, filename, 0600)`,

which should work even without permissions to the file. However when that syscall is passed to fuse-overlayfs, it is translated into the following syscalls for the underlying NFS:

- `fd = openat2(dirfd, filename, O_RDONLY)`
- `fchmod(fd, 0600)`

On NFS filesystem the `openat2` call requires read permissions for the file, so it fails with error "permission denied".

Interestingly, `openat2` doesn't need read permissions on ext4 filesystem so that's why the bug does not appear there.

The relevant section of code is here:
https://github.com/containers/fuse-overlayfs/blob/dedd8410ed0dd52150c98a9d666b875388f5395e/main.c#L3985-L3990

**Comment by rhatdan** [comment]
Do you think this is a bug in the kernel?  IE Should EXT4 require the read access or NFS Not require read access?

**Comment by ollpu** [comment]
> Should EXT4 require the read access

Yes, according to various documentation, e.g. POSIX `open`:

> These functions shall fail if:
>
> EACCES
>    Search permission is denied on a component of the path prefix, **or the file exists and the permissions specified by oflag are denied**

And even more explicitly in `open(2)`, under the documentation for the non-POSIX `O_PATH` flag:

> By contrast, obtaining a reference to a filesystem object by opening it with the O_RDONLY flag requires that the caller have read permission on the object, even when the subsequent operation (e.g., fchdir(2), fstat(2)) does not require read permission on the object.

In any case, it might be something that won't be changed because of backwards compatibility. Reading from the file descriptor is still prevented.

**Comment by Tuupertunut** [comment]
I created a PR #350 with a simple fix for this.
