### ISSUE TITLE
fusermount3: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

### ISSUE THREAD

**Issue by siretart** [containers/fuse-overlayfs#35]
I'm trying to package this application for Debian (cf. http://bugs.debian.org/917889). While trying it out, I'm running into this issue:

```
./fuse-overlayfs -o lowerdir=/ -o upperdir=/tmp/upper/ -o workdir=/tmp/overlay-workdir/ /tmp/overlay
UID=unchanged
GID=unchanged
UPPERDIR=/tmp/upper
WORKDIR=/tmp/overlay-workdir/
LOWERDIR=/
MOUNTPOINT=/tmp/overlay
fusermount3: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
./fuse-overlayfs: cannot mount: Operation not permitted
```

After editing `/etc/fuse.conf` to enable the option `user_allow_other`, the program appears to work. Unfortunately, this is not the default setting in Debian. My questions here are:

1. Is there any way to modify the program to work without editing `/etc/fuse.conf`?
2. What are the security ramifications for enabling this option?
3. Does RHEL8 enable this option by default? - If no, is the superuser expected to do that modification himself?

Thank you

**Comment by giuseppe** [comment]
the `user_allow_other` is required to have multiple users inside of the container that can use the file system.  Otherwise fuse-overlayfs will be usable only by the user that is mapped to the unprivileged user on the host (usually root in the container).

**Comment by siretart** [comment]
On Fri, Jan 4, 2019, 03:02 Giuseppe Scrivano <notifications@github.com
wrote:

> the user_allow_other is required to have multiple users inside of the
> container that can use the file system. Otherwise fuse-overlayfs will be
> usable only by the user that is mapped to the unprivileged user on the host
> (usually root in the container).
>

In my tests, that option is required for the program to work at all. Is
that expected or a bug?

**Comment by giuseppe** [comment]
it is expected

**Comment by rhatdan** [comment]
Should we document this in podman docs?

**Comment by rhatdan** [comment]
@giuseppe Can you open a PR against Podman and here to document the issue.

**Comment by siretart** [comment]
May I ask to clarify why this additional step is necessary? What are the security tradeoffs / implications by adding this option to `/etc/fuse.conf`?

I imagine the answer to this question should be included in the documentaiton.

**Comment by giuseppe** [comment]
it looks like when running in an user namespace the option in `/etc/fuse.conf` is not necessary.  I could run fuse-overlayfs from podman without having `user_allow_other`.

So it seems it is failing only when running with an UID != 0.  In this case we don't probably want to use `user_allow_other` by default.

Could you check if https://github.com/containers/fuse-overlayfs/pull/39 works for you?
