### ISSUE TITLE
Wrong flag value for RENAME_NOREPLACE

### ISSUE THREAD

**Issue by Tuupertunut** [containers/fuse-overlayfs#353]
I think the value for the flag RENAME_NOREPLACE is wrong in the source.

https://github.com/containers/fuse-overlayfs/blob/878cb0ccad071d4adda506db3147b3bcefdff27e/main.c#L127-L130

In the linux kernel source it is `1 << 0`

https://github.com/torvalds/linux/blob/f2906aa863381afb0015a9eb7fefad885d4e5a56/include/uapi/linux/fs.h#L50-L52

This isn't usually a problem as the constant is already defined, but a bug anyway.

**Comment by flouthoc** [comment]
Actually this indeed looks wrong to me as well and this could also conflict with `RENAME_WHITEOUT` as well if both `RENAME_WHITEOUT` and `RENAME_EXCHANGE` are undefined https://github.com/containers/fuse-overlayfs/blob/main/main.c#L133 @giuseppe WDYT ?

**Comment by giuseppe** [comment]
yes, it seems to have the wrong value.

Would you mind opening a PR to fix it?
