### ISSUE TITLE
Missing whiteout when renaming file over existing whiteout

### ISSUE THREAD

**Issue by Tuupertunut** [containers/fuse-overlayfs#354]
**How to reproduce:**

```bash
unshare --mount --user --map-root-user bash -c '
    mkdir lower upper work mount
    touch lower/testfile
    touch lower/testfile2
    fuse-overlayfs -o squash_to_root -o lowerdir=lower,upperdir=upper,workdir=work mount
    rm mount/testfile2
    touch mount/testfile
    mv mount/testfile mount/testfile2
    fusermount -uz mount
'
```

**Expected behavior:**

After the mv there should be a whiteout shadowing `testfile` in `upper`.

**Actual behavior:**

The whiteout is missing.

**Why this happens:**

If there is already a whiteout in the destination path, and `rename` is called with flag `RENAME_NOREPLACE`, there is a special handling in the code for this case, but it does not create a whiteout to the source path like in all other cases.

See this code:

https://github.com/containers/fuse-overlayfs/blob/878cb0ccad071d4adda506db3147b3bcefdff27e/main.c#L4636

In this branch there is no code for creating a whiteout like in all other branches.

**Comment by flouthoc** [comment]
@Tuupertunut Could you please try the patch in PR https://github.com/containers/fuse-overlayfs/pull/356 this is still in draft since this needs review.
