### ISSUE TITLE
copy_file_range fails when copying from a deleted file

### ISSUE THREAD

**Issue by SpecLad** [containers/fuse-overlayfs#368]
Run the following program with the working directory set to a fuse-overlayfs mount:

```c
#define _GNU_SOURCE

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

#include <stdio.h>

int main() {
    int source_fd = open("source.txt", O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
    unlink("source.txt");
    write(source_fd, "test\n", 5);
    lseek(source_fd, 0, SEEK_SET);

    int dest_fd = open("destination.txt", O_WRONLY | O_CREAT, S_IRUSR | S_IWUSR);

    if (copy_file_range(source_fd, NULL, dest_fd, NULL, 5, 0) < 0) {
        perror("copy_file_range");
        return 1;
    }

    puts("ok");
    return 0;
}
```

The output is:

```
copy_file_range: No such file or directory
```

On a regular file system the program completes successfully.

**Comment by SpecLad** [comment]
This bug breaks bash heredocs in certain cases. Specifically, a script like this:

```bash
cat > foobar.txt <<"EOF"
<text here>
EOF
```

will fail with a bizarre error:

```
cat: -: No such file or directory
```

if all of these are true:

* `/tmp` is on a `fuse-overlayfs` system (which happens when running in a container);
* `cat` comes from Coreutils 9.1 or later;
* the size of the text is greater than 65536 bytes.

**Comment by SpecLad** [comment]
Version information:

```
fuse-overlayfs: version 1.9
FUSE library version 3.10.5
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.5
```

**Comment by giuseppe** [comment]
thanks for the report and the reproducer.

Opened a PR: https://github.com/containers/fuse-overlayfs/pull/369
