### ISSUE TITLE
v0.7.x release for CentOS 7

### ISSUE THREAD

**Issue by ketan-vijayvargiya** [containers/fuse-overlayfs#379]
Hi,

We are currently running version 0.7.2 in one of our production environments and are hitting a bug which is already fixed by #164. 

However, the latest version of fuse-overlayfs for the Linux distribution we use - CentOS 7 - is 0.7.2 as you can see [here](https://pkgs.org/download/fuse-overlayfs). Ideally, if there were 0.7.3 (or any 0.7.x), we could have pulled that in to fix the issue at our end.

I do see [v0.7.3](https://github.com/containers/fuse-overlayfs/releases/tag/v0.7.3) on GitHub. So, I am trying to figure out what are the steps to release 0.7.3 or 0.7.x upstream to CentOS's package distribution.

If someone here can provide guidance, I am happy to look into this further and do the necessary work. Appreciate the help.

Thanks.

**Comment by debarshiray** [comment]
I suspect that you would have to get 0.7.3 into RHEL 7 and then it will propagate down to CentOS 7.  However, that might be easier said than done, unless you are using RHEL 7 itself.
