### ISSUE TITLE
change fuse-overlayfs license to GPL2

### ISSUE THREAD

**Issue by rsciuk** [containers/fuse-overlayfs#387]
In creating a device based container infrastructure, we are using crun, and would like to also incorporate the fuse-overlayfs.  While crun is licensed under GPL2, fuse-overlayfs is GPL3.  Our policies prevent use of GPL3 code, but GPL2 is acceptable to our "powers that be". 

Giuseppe is onboard with a change to GPL2, but requires the approval of contributors in order to make the change. Are there any reasons why the fuse-overlayfs could not be licensed as GPL2 as is the crun runtime, or objections in doing so?

**Comment by rhatdan** [comment]
Not by me. I approve.

**Comment by rhatdan** [comment]
You need approval by all contributors which are only 
@nalind @rhvgoyal @giuseppe and me need to approve.

**Comment by giuseppe** [comment]
ACK from me.

We need a ACK from:

$ git log  --format='- [ ] %an' *.[hc] | sort  | uniq 
- [ ] Aditya R
- [ ] Andrei Gherzan
- [ ] Asaf Kahlon
- [ ] cptpcrd
- [x] Daniel J Walsh
- [ ] David Hedberg
- [ ] Denys Vitali
- [ ] Erik Sipsma
- [ ] Fabrice Fontaine
- [x] Giuseppe Scrivano
- [ ] Jonathan Calmels
- [ ] Max Goltzsche
- [ ] Nate Coraor
- [ ] Nathaniel Wesley Filardo
- [ ] Patrick J. LoPresti
- [ ] Sascha Grunert
- [ ] Shotaro Gotanda
- [ ] Stephane Thiell
- [ ] Tuupertunut
- [ ] Tyler Ramer

@flouthoc @dhedberg @agherzan @asafkahlon @cptpcrd @sipsma @denysvitali @ffontaine @3XX0 @mgoltzsche @natefoo @nwf @plopresti @saschagrunert @sgotand @thiell @Tuupertunut @tylarb are you fine to change the license from GPLv3 to GPLv2?

**Comment by ffontaine** [comment]
I agree

**Comment by dhedberg** [comment]
GPLv2 is fine with me.

**Comment by agherzan** [comment]
All good on my side.

**Comment by denysvitali** [comment]
Fine for me :)

**Comment by saschagrunert** [comment]
SGTM

**Comment by 3XX0** [comment]
Agreed

**Comment by flouthoc** [comment]
SGTM

**Comment by cptpcrd** [comment]
Fine by me

**Comment by nwf** [comment]
Can you clarify if this is a change to GPLv2-only or GPLv2-or-later?

**Comment by giuseppe** [comment]
sorry for not being clearer: version 2 or later

**Comment by plopresti** [comment]
Yes, this is fine.

**Comment by tylarb** [comment]
yes - good with me.

**Comment by mgoltzsche** [comment]
yes, fine with me

**Comment by thiell** [comment]
I agree.

**Comment by nwf** [comment]
While I think that the GPLv3 better embodies the FSF's mission, if you want GPLv2-or-later who am I to say no, given my very minimal contribution to this project.  +1

**Comment by Tuupertunut** [comment]
It is fine.

**Comment by rsciuk** [comment]
Thanks, Daniel. Much appreciated.
________________________________

**Comment by natefoo** [comment]
+1 from me

**Comment by giuseppe** [comment]
@agherzan @sipsma @sgotand we miss just yours :) Are you fine with the license change?

**Comment by sipsma** [comment]
Yep, all good!

**Comment by agherzan** [comment]
> All good on my side.

I did reply above. I approve this twice :)

**Comment by rhatdan** [comment]
@sgotand @asafka7 Are still missing.

**Comment by giuseppe** [comment]
27a01e622e1f26b3c60137c3123c0b667b3f6579 is a trivial change, not sure we need to worry about asking for the permission to change license.

@sgotand contributions are multiple lines so we need to wait for that.

**Comment by rsciuk** [comment]
No word yet from @sgotand?

**Comment by asafkahlon** [comment]
SGTM

**Comment by rhatdan** [comment]
Down to one ...

**Comment by rsciuk** [comment]
Still crickets?

**Comment by giuseppe** [comment]
the legal team confirmed these changes are too trivial to be copyrightable so we can move forward and change to GPLv2+

**Comment by giuseppe** [comment]
PR: https://github.com/containers/fuse-overlayfs/pull/392

**Comment by rsciuk** [comment]
Thanks Giuseppe.  Much appreciated.
________________________________
