### ISSUE TITLE
Calling fuse-overlayfs in a systemd user service fails to mount anything

### ISSUE THREAD

**Issue by graysky2** [containers/fuse-overlayfs#388]
If I run the following script from a shell, the mount is created as expected.  If I call the same script from a systemd user service, `fuse-overlayfs` does not create the mount and does not throw an error code.  Is this expected or a bug?

Place this in `/usr/local/bin/testmount`:
```
#!/bin/bash

LOW=/scratch/low
UP=/scratch/.up
WORK=/scratch/.work
TARGET=/scratch/merged

[[ -d "$LOW" ]] || mkdir "$LOW"
[[ -d "$UP" ]] || mkdir "$UP"
[[ -d "$WORK" ]] || mkdir "$WORK"
[[ -d "$TARGET" ]] || mkdir "$TARGET"

if ! mountpoint -q "$TARGET"; then
	fuse-overlayfs -o lowerdir="$LOW",upperdir="$UP",workdir="$WORK" "$TARGET"
else
	echo "already mount"
fi
```

You should create `/scratch` as root and chown/chmod it to your user name.

Place this in `~/.config/systemd/user/testmount.service`:
```
[Unit]
Description=test mount

[Service]
ExecStart=/usr/local/bin/testmount

[Install]
WantedBy=multi-user.target
```

Run:
```
systemctl --user daemon-reload
```

Start the service:
```
systemctl --user start testmount
```

**Comment by graysky2** [comment]
Related?  https://github.com/systemd/systemd/issues/17607

**Comment by giuseppe** [comment]
maybe you'd like to run fuse-overlayfs in foreground mode?  `fuse-overlayfs -f`.

Otherwise it will daemonize itself and the main process exits, confusing systemd

**Comment by graysky2** [comment]
I found a solution by adding `RemainAfterExit=yes` to the service.  https://github.com/graysky2/profile-sync-daemon/commit/6c925e4e4df9c118b538987bf95fc0c7aac6f345
