### ISSUE TITLE
Extraneous "/proc seems to be mounted as readonly, it can lead to unexpected failures"

### ISSUE THREAD

**Issue by DrDaveD** [containers/fuse-overlayfs#397]
In one case on EL8 I am consistently getting an extraneous warning message from fuse-overlayfs-1.11:
```
/proc seems to be mounted as readonly, it can lead to unexpected failures"
```
I checked the [code](https://github.com/containers/fuse-overlayfs/blob/main/main.c#L319) and it appears to be to be looking at a statvfs structure which is never initialized.  I'm not sure what it is supposed to be doing or what the check is for, but it is apparently not doing what it is supposed to do.

**Comment by giuseppe** [comment]
thanks for the report, opened a PR: https://github.com/containers/fuse-overlayfs/pull/398
