### ISSUE TITLE
Make with Fuse 2

### ISSUE THREAD

**Issue by zh324** [containers/fuse-overlayfs#416]
Hi all,

I am pretty new to container and linux build. Get some questions for you: 
1. My current linux kernel version is 3.10.0 so I try to compile fuse-overlayfs with fuse-2.9.7.
Is this technically possible? I am using centOS 7 so I changed the container file to use centos7.9.2009.

2.  I have encountered some errors for my naive try, for example: 

```
make[4]: Leaving directory `/build/fuse-overlayfs/lib'
make[3]: Leaving directory `/build/fuse-overlayfs/lib'
make[2]: Leaving directory `/build/fuse-overlayfs/lib'
make[2]: Entering directory `/build/fuse-overlayfs'
gcc -DHAVE_CONFIG_H -I.  -DPKGLIBEXECDIR='"/usr/libexec/fuse-overlayfs"'  -I . -I /build/fuse-overlayfs/lib  -g -O2 -MT fuse_overlayfs-main.o -MD -MP -MF .deps/fuse_overlayfs-main.Tpo -c -o fuse_overlayfs-main.o `test -f 'main.c' || echo './'`main.c
main.c: In function 'ovl_init':
main.c:460:24: error: 'FUSE_CAP_WRITEBACK_CACHE' undeclared (first use in this function)
   if ((conn->capable & FUSE_CAP_WRITEBACK_CACHE) == 0)
                        ^
main.c:460:24: note: each undeclared identifier is reported only once for each function it appears in
main.c:463:44: error: 'FUSE_CAP_POSIX_ACL' undeclared (first use in this function)
   if ((lo->noacl == 0) && (conn->capable & FUSE_CAP_POSIX_ACL))
                                            ^
```

Maybe you can help direct me to the correct path? 

Thank you so much!

**Comment by giuseppe** [comment]
that is not supported and we are not going to add support for it as it is quite different than fuse 3

**Comment by zh324** [comment]
> that is not supported and we are not going to add support for it as it is quite different than fuse 3

thanks for the quick answer!
