### ISSUE TITLE
musl build failure

### ISSUE THREAD

**Issue by CameronNemo** [containers/fuse-overlayfs#50]
FTBFS with musl libc

```
cc -DHAVE_CONFIG_H -I.    -I . -I /builddir/fuse-overlayfs-0.3/lib -I/usr/include/fuse3 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT fuse_overlayfs-main.o -MD -MP -MF .deps/fuse_overlayfs-main.Tpo -c -o fuse_overlayfs-main.o `test -f 'main.c' || echo './'`main.c
main.c:39:10: fatal error: error.h: No such file or directory
 #include <error.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:571: fuse_overlayfs-main.o] Error 1
```

https://travis-ci.org/void-linux/void-packages/jobs/498513645

**Comment by CameronNemo** [comment]
My first thought is just adding a stub error() implementation. There are 20 uses of the function throughout the overlayfs module. Would you like me to take any special considerations into case when forming a patch?

**Comment by giuseppe** [comment]
could you copy the implementation from gnulib?
It is already implemented there for systems where `error` is missing

**Comment by giuseppe** [comment]
alternatively, I am fine if we take rid of `error` and replace with fprintf (stderr, ...) + exit ();

**Comment by giuseppe** [comment]
@CameronNemo I've opened a PR here: https://github.com/containers/fuse-overlayfs/pull/52

**Comment by mgoltzsche** [comment]
This is an issue again at least since `<error.h>` is used in [plugin_manager.c](https://github.com/containers/fuse-overlayfs/blob/b28a23a39d8b3b7346bf30c78ca758b9e30b0e2d/plugin-manager.c#L22) which is not supported by musl. Instead it should use `<err.h>` like [this](https://github.com/linux-can/can-utils/pull/163/files).

**Comment by CameronNemo** [comment]
#147
