### ISSUE TITLE
man page doesn't mention uidmapping or gidmapping

### ISSUE THREAD

**Issue by DrDaveD** [containers/fuse-overlayfs#54]
I wanted to understand how uidmapping and gidmapping options work, so I checked the man page, but there's nothing there.

**Comment by DrDaveD** [comment]
Also I don't see it in the help message.

**Comment by giuseppe** [comment]
@DrDaveD could you please check if https://github.com/containers/fuse-overlayfs/pull/56 is clear enough?

**Comment by DrDaveD** [comment]
I added my comments in a review on #56.
