### ISSUE TITLE
Be less noisy

### ISSUE THREAD

**Issue by ihucos** [containers/fuse-overlayfs#57]
Hello,

maybe it makes sense to remove this output to stderr: https://github.com/containers/fuse-overlayfs/blob/a6958ce78fdabd75b7db4e9a6e03177b01734f8d/main.c#L3883

It is kind of noisy since its printed on every invocation and echoes parameters. Maybe only show it if some debugging flag is specified?

Cheers

ihucos

**Comment by giuseppe** [comment]
agreed.  I've opened a PR to address it: https://github.com/containers/fuse-overlayfs/pull/58
