### ISSUE TITLE
Multiple flock calls on the same filename deadlocks

### ISSUE THREAD

**Issue by basvdlei** [containers/fuse-overlayfs#80]
When flock calls are made from multiple processes for the same filename fuse-overlayfs deadlocks.

This happens reliably when running multiple `git clones` or `go get` from a rootless container in Fedora Silverblue:

```
● ostree://fedora-workstation:fedora/30/x86_64/silverblue
                   Version: 30.20190530.0 (2019-05-30T00:39:27Z)
                BaseCommit: 8980028d1ac8f8180b29233be4704d0ff3c8e01d6833d149dc460919a63c39a7
```

Backtrace of hanging `/usr/bin/fuse-overlayfs`:
```c
#0  0x00007f68d23a647b in flock () from target:/lib64/libc.so.6
#1  0x00000000004031be in ovl_flock ()
#2  0x00007f68d24b71ba in ?? () from target:/lib64/libfuse3.so.3
#3  0x00007f68d24b9908 in ?? () from target:/lib64/libfuse3.so.3
#4  0x00007f68d24b4c2b in fuse_session_loop () from target:/lib64/libfuse3.so.3
#5  0x0000000000402c56 in main ()
```

It's probably related to the following section in the flock(2) manpage:

> If a process uses open(2) (or similar) to obtain more than one file descriptor for the same file, these file descriptors are treated independently by flock(). *An attempt to lock the file using one of these file descriptors may be denied by a lock that the calling process has already placed via another file descriptor.*

Maybe related to #67 

## How to reproduce

Running the following program in a rootless container concurrently hangs that container.

**fuse-overlay-flock.c**
```c
#include <sys/file.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char* argv[])
{
	int fd;
	fd = open(argv[1], O_CREAT|O_WRONLY, 0644);
	flock(fd, LOCK_EX);
	dprintf(fd, "foo\n");
	flock(fd, LOCK_UN);
	close(fd);
	printf("done\n");
	return 0;
}
```

**Dockerfile**:
```dockerfile
FROM registry.fedoraproject.org/fedora:30
RUN dnf install -y gcc
COPY fuse-overlay-flock.c /
RUN gcc -o fuse-overlay-flock fuse-overlay-flock.c
ENTRYPOINT [ "/usr/bin/bash" ]
CMD [ "-c", "for i in $(seq 1 10); do ( /fuse-overlay-flock testfile & ); done" ]
````

**Command**:
```bash
podman build -t localhost/fuse-overlay-bug:latest
podman run --rm -it localhost/fuse-overlay-bug:latest
```

### Actual result

```bash
$ podman run --rm -it localhost/fuse-overlay-bug:latest
done
```

The container does not print the other 'done' messages and never exits. It will only stop when the relevant fuse-overlayfs process is killed.

### Expected result

```bash
$ podman run --rm -it localhost/fuse-overlay-bug:latest
done
done
done
done
done
done
done
done
done
done
$
```

**Comment by 3XX0** [comment]
I experienced it too, package managers tend to do that and end up deadlocked.

**Comment by giuseppe** [comment]
thanks for the amazing reproducer, it was very easy to reproduce locally and see immediately the issue.  

I've opened a PR here: https://github.com/containers/fuse-overlayfs/pull/82

Could you verify if it works for you?  I've done some tests based on your code and the locking seems to work fine (if I had a sleep while we hold the lock, I can see other processes are waiting for it)

**Comment by basvdlei** [comment]
Thanks! It's always nice when removing code solves an issue :-)

I can no longer reproduce this issue with your patch applied. As far as I can tell, it also (still) does the right thing when flock is called on a file in a lower fs. That is: a flock call on a file in the container image from one container does not result in a locked file for a second container.

**Comment by giuseppe** [comment]
> Thanks! It's always nice when removing code solves an issue :-)

yes, I don't remember last time I could literally delete the bug :-)

**Comment by rhatdan** [comment]
Time for a new release?

**Comment by giuseppe** [comment]
> Time for a new release?

working on one: https://github.com/containers/fuse-overlayfs/pull/84
