### ISSUE TITLE
`do_rm` fails to remove directories in upper layer (if whiteouts present?)

### ISSUE THREAD

**Issue by mbargull** [containers/fuse-overlayfs#93]
Test case:
```sh
container="$( buildah from -q debian:10-slim )"
buildah run "${container}" sh -ec 'apt-get update -qq && apt-get install -qqy time'
buildah run "${container}" rm -rf /usr/share/zoneinfo
```
Removing directories in an upper layer fails with, e.g.,
```
/bin/rm: cannot remove '/usr/share/zoneinfo/Australia/Adelaide': Is a directory
```
where `/usr/share/zoneinfo/Australia/Adelaide` is actually a file, not a directory.

gh-89 introduced a bug such that `do_rm` might not call `empty_dir` and not remove `.wh.*` files from a folder.

Used builds:
- `/tmp/fuse-overlayfs-7bc2dd9`: release 0.4.2
- `/tmp/fuse-overlayfs-95e1d01`: gh-88
- `/tmp/fuse-overlayfs-bd9eb8d`: gh-89
- `/tmp/fuse-overlayfs-9c77da7`: gh-91
- `/tmp/fuse-overlayfs-4e32e89`: gh-92

Full test case:
<details open><summary>

```sh
buildah_fuse_overlayfs() {
  local fuse_overlayfs_bin
  fuse_overlayfs_bin="${1}"
  shift
  buildah --runroot=/tmp/containers-tmp --root=/tmp/containers-tmp --storage-opt=overlay.mount_program="${fuse_overlayfs_bin}" "${@}"
}
for fuse_overlayfs_bin in \
    /tmp/fuse-overlayfs-7bc2dd9 \
    /tmp/fuse-overlayfs-95e1d01 \
    /tmp/fuse-overlayfs-bd9eb8d \
    /tmp/fuse-overlayfs-9c77da7 \
    /tmp/fuse-overlayfs-4e32e89 \
    ; do
  echo "${fuse_overlayfs_bin}"
  container="$( buildah_fuse_overlayfs "${fuse_overlayfs_bin}" from -q debian:10-slim )"
  buildah_fuse_overlayfs "${fuse_overlayfs_bin}" run "${container}" sh -ec 'apt-get update -qq && apt-get install -qqy time >/dev/null 2>&1'
  buildah_fuse_overlayfs "${fuse_overlayfs_bin}" run "${container}" rm -rf /usr/share/zoneinfo || true
  buildah_fuse_overlayfs "${fuse_overlayfs_bin}" rm  "${container}" >/dev/null
done
```
</summary>

```
/tmp/fuse-overlayfs-7bc2dd9
/tmp/fuse-overlayfs-95e1d01
/tmp/fuse-overlayfs-bd9eb8d
/bin/rm: cannot remove '/usr/share/zoneinfo/Australia/Adelaide': Is a directory
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
/tmp/fuse-overlayfs-9c77da7
/bin/rm: cannot remove '/usr/share/zoneinfo/EST': Is a directory
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
/tmp/fuse-overlayfs-4e32e89
/bin/rm: cannot remove '/usr/share/zoneinfo/Australia/NSW': Is a directory
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
```
</details>

Partially reverting 605e17fbf726b7b1c57f155b9b9c11de8a9b7d17, i.e., removing https://github.com/containers/fuse-overlayfs/pull/89/commits/605e17fbf726b7b1c57f155b9b9c11de8a9b7d17#diff-2045016cb90d1e65d71c2407a2570927R2607 fixes the issue.
However, I'm not sure this would be correct. If I understand `do_rm`, `count_dir_entries` and `empty_dir` correctly, the change from that commit makes sense. Which would imply that there is an inconsistency between `node->children` (whiteout) nodes and actual present `.wh.*` files.

(... and that's as far as I can analyze the problem without reading all of the code ;). )

**Comment by giuseppe** [comment]
thanks for the very detailed report!  The issue happens because of `87deb1d4585129adc222a778c978f08936368784`

I've opened a PR to address the issue and make sure the work directory is cleaned up: https://github.com/containers/fuse-overlayfs/pull/94
